INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2236, 6, 3, 'Avalie o estado de conservação dos itens e equipamentos do prédio - Telhado', 7);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2236, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2236, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2236, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2236, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2237, 6, 3, 'Avalie o estado de conservação dos itens e equipamentos do prédio - Paredes', 8);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2237, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2237, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2237, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2237, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2238, 6, 3, 'Avalie o estado de conservação dos itens e equipamentos do prédio - Piso', 9);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2238, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2238, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2238, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2238, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2239, 6, 3, 'Avalie o estado de conservação dos itens e equipamentos do prédio - Entrada do prédio', 10);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2239, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2239, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2239, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2239, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2240, 6, 3, 'Avalie o estado de conservação dos itens e equipamentos do prédio - Pátio', 11);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2240, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2240, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2240, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2240, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2241, 6, 3, 'Avalie o estado de conservação dos itens e equipamentos do prédio - Corredores', 12);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2241, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2241, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2241, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2241, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2242, 6, 3, 'Avalie o estado de conservação dos itens e equipamentos do prédio - Salas de aula', 13);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2242, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2242, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2242, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2242, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2243, 6, 3, 'Avalie o estado de conservação dos itens e equipamentos do prédio - Portas', 14);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2243, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2243, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2243, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2243, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2244, 6, 3, 'Avalie o estado de conservação dos itens e equipamentos do prédio - Janelas', 15);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2244, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2244, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2244, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2244, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2245, 6, 3, 'Avalie o estado de conservação dos itens e equipamentos do prédio - Banheiros', 16);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2245, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2245, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2245, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2245, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2246, 6, 3, 'Avalie o estado de conservação dos itens e equipamentos do prédio - Cozinha', 17);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2246, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2246, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2246, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2246, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2247, 6, 3, 'Avalie o estado de conservação dos itens e equipamentos do prédio - Instalações Hidráulicas', 18);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2247, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2247, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2247, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2247, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2248, 6, 3, 'Avalie o estado de conservação dos itens e equipamentos do prédio - Instalações Elétricas', 19);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2248, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2248, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2248, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2248, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2249, 6, 3, 'Avalie a quantidade de salas de aula que atendem aos seguintes critérios: São iluminadas de forma adequada. (Observe se a iluminação natural ou artificial garante boa claridade no interior das salas.)', 20);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2249, 'A', 'Todas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2249, 'B', 'Mais da metade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2249, 'C', 'Menos da metade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2249, 'D', 'Nenhuma.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2250, 6, 3, 'Avalie a quantidade de salas de aula que atendem aos seguintes critérios: São arejadas de forma adequada.', 21);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2250, 'A', 'Todas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2250, 'B', 'Mais da metade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2250, 'C', 'Menos da metade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2250, 'D', 'Nenhuma.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2251, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Controle de entrada e saída de alunos.', 22);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2251, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2251, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2251, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2251, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2252, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Controle de entrada de pessoas estranhas na escola.', 23);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2252, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2252, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2252, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2252, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2253, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Vigilância para o período diurno.', 24);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2253, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2253, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2253, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2253, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2254, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Vigilância para o período noturno.', 25);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2254, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2254, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2254, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2254, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2255, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Vigilância para os finais de semana e feriados.', 26);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2255, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2255, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2255, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2255, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2256, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Esquema de policiamento para inibição de furtos, roubos e outras formas de violência.', 27);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2256, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2256, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2256, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2256, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2257, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Esquema de policiamento para inibição de tráfico de tóxicos/drogas dentro da escola.', 28);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2257, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2257, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2257, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2257, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2258, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Esquema de policiamento para inibição de tráfico de tóxicos/drogas nas imediações da escola.', 29);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2258, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2258, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2258, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2258, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2259, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Sistema de proteção contra incêndio (alarme de fumaça e temperatura, extintores contra incêndio dentro do
prazo de validade, mangueiras etc.).Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Sistema de proteção contra incêndio (alarme de fumaça e temperatura, extintores contra incêndio dentro do
prazo de validade, mangueiras etc.).Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Sistema de proteção contra incêndio (alarme de fumaça e temperatura, extintores contra incêndio dentro do
prazo de validade, mangueiras etc.).Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Sistema de proteção contra incêndio (alarme de fumaça e temperatura, extintores contra incêndio dentro do
prazo de validade, mangueiras etc.).', 30);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2259, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2259, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2259, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2259, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2260, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Iluminação do lado de fora da escola.', 31);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2260, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2260, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2260, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2260, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2261, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Há muros, grades ou cercas em condições de garantir a segurança dos alunos? (Caso existam buracos ou aberturas que permitam o acesso de estranhos, responder NÃO.)', 32);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2261, 'A', 'Sim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2261, 'B', 'Não');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2262, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Os equipamentos mais caros (computadores, projetores, televisão, vídeo etc.) são guardados em salas seguras ou possuem mecanismos de proteção (cadeados, grades, travas, trancas etc.)?', 33);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2262, 'A', 'Sim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2262, 'B', 'Não');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2263, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: Os portões que dão acesso à parte externa permanecem trancados durante o horário de funcionamento da escola?', 34);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2263, 'A', 'Sim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2263, 'B', 'Não');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2264, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: A escola adota alguma medida de segurança para proteger os alunos nas suas imediações?', 35);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2264, 'A', 'Sim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2264, 'B', 'Não');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2265, 6, 3, 'Avalie os seguintes aspectos em relação à segurança da escola e dos alunos: A escola apresenta sinais de depredação (vidros, portas e janelas quebradas, lâmpadas estouradas etc.)?', 36);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2265, 'A', 'Sim, muita.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2265, 'B', 'Sim, pouca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2265, 'C', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2266, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Computadores para uso dos alunos. ', 37);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2266, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2266, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2266, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2266, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2267, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Acesso à internet para uso dos alunos.', 38);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2267, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2267, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2267, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2267, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2268, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Computadores para uso dos professores.', 39);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2268, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2268, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2268, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2268, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2269, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Acesso à internet para uso dos professores.', 40);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2269, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2269, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2269, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2269, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2270, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Computadores exclusivamente para o uso administrativo.', 41);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2270, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2270, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2270, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2270, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2271, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Fitas de vídeo ou dvd (educativas).', 42);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2271, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2271, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2271, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2271, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2272, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Fitas de vídeo ou dvd (lazer).', 43);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2272, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2272, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2272, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2272, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2273, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Máquina copiadora.', 44);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2273, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2273, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2273, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2273, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2274, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Impressora.', 45);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2274, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2274, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2274, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2274, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2275, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Retroprojetor.', 46);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2275, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2275, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2275, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2275, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2276, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Projetor de slides.', 47);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2276, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2276, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2276, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2276, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2277, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Videocassete ou aparelho de dvd.', 48);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2277, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2277, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2277, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2277, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2278, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Televisão.', 49);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2278, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2278, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2278, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2278, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2279, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Mimeógrafo.', 50);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2279, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2279, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2279, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2279, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2280, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Câmera fotográfica.', 51);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2280, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2280, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2280, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2280, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2281, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Antena parabólica.', 52);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2281, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2281, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2281, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2281, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2282, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Internet com conexão Banda Larga.', 53);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2282, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2282, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2282, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2282, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2283, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Linha telefônica.', 54);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2283, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2283, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2283, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2283, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2284, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Aparelho de fax.', 55);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2284, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2284, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2284, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2284, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2285, 6, 3, 'Indique se nesta escola existem ou não os recursos apontados e quais são suas condiçoes de uso. Aparelho de som.', 56);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2285, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2285, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2285, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2285, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2286, 6, 3, 'Indique a existência e as condições de uso dos seguintes espaços da escola: Biblioteca.', 57);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2286, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2286, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2286, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2286, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2287, 6, 3, 'Indique a existência e as condições de uso dos seguintes espaços da escola: Sala de leitura.', 58);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2287, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2287, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2287, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2287, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2288, 6, 3, 'Indique a existência e as condições de uso dos seguintes espaços da escola: Quadra de esportes.', 59);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2288, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2288, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2288, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2288, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2289, 6, 3, 'Indique a existência e as condições de uso dos seguintes espaços da escola: Laboratório de informática.', 60);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2289, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2289, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2289, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2289, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2290, 6, 3, 'Indique a existência e as condições de uso dos seguintes espaços da escola: Laboratório de Ciências.', 61);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2290, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2290, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2290, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2290, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2291, 6, 3, 'Indique a existência e as condições de uso dos seguintes espaços da escola: Auditório.', 62);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2291, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2291, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2291, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2291, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2292, 6, 3, 'Indique a existência e as condições de uso dos seguintes espaços da escola: Sala para atividades de música.', 63);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2292, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2292, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2292, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2292, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2293, 6, 3, 'Indique a existência e as condições de uso dos seguintes espaços da escola: Sala para atividades de artes pláticas.', 64);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2293, 'A', 'Bom');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2293, 'B', 'Regular');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2293, 'C', 'Ruim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2293, 'D', 'Inexistente');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2294, 6, 3, 'Em relação à biblioteca ou sala de leitura:  Possui acervo diversificado que desperte o interesse dos alunos.', 65);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2294, 'A', 'Sim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2294, 'B', 'Não');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2294, 'C', 'Não há biblioteca/sala de leitura.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2295, 6, 3, 'Em relação à biblioteca ou sala de leitura:  Possui brinquedoteca.', 66);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2295, 'A', 'Sim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2295, 'B', 'Não');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2295, 'C', 'Não há biblioteca/sala de leitura.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2296, 6, 3, 'Em relação à biblioteca ou sala de leitura:  Possui espaço para estudos coletivos.', 67);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2296, 'A', 'Sim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2296, 'B', 'Não');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2296, 'C', 'Não há biblioteca/sala de leitura.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2297, 6, 3, 'Em relação à biblioteca ou sala de leitura:  Os livros podem ser manuseados e emprestados.', 68);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2297, 'A', 'Sim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2297, 'B', 'Não');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2297, 'C', 'Não há biblioteca/sala de leitura.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2298, 6, 3, 'Em relação à biblioteca ou sala de leitura:  A comunidade pode  utilzar o espaço e os livros.', 69);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2298, 'A', 'Sim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2298, 'B', 'Não');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2298, 'C', 'Não há biblioteca/sala de leitura.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2299, 6, 3, 'Em relação à biblioteca ou sala de leitura:  O espaço é arejado e bem iluminado.', 70);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2299, 'A', 'Sim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2299, 'B', 'Não');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2299, 'C', 'Não há biblioteca/sala de leitura.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2300, 6, 3, 'Em relação à biblioteca ou sala de leitura:  Existe uma pessoa responsável pelo atendimento na biblioteca ou na sala de leitura.', 71);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2300, 'A', 'Sim');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2300, 'B', 'Não');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2300, 'C', 'Não há biblioteca/sala de leitura.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2301, 6, 3, 'Os seguintes usuários da biblioteca (ou sala de leitura) levam livros para casa: Os alunos:', 72);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2301, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2301, 'B', 'Não, porque não querem');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2301, 'C', 'Não, porque a escola não permite');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2301, 'D', 'Não há biblioteca/sala de leitura.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2302, 6, 3, 'Os seguintes usuários da biblioteca (ou sala de leitura) levam livros para casa: Os professores:', 73);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2302, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2302, 'B', 'Não, porque não querem');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2302, 'C', 'Não, porque a escola não permite');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2302, 'D', 'Não há biblioteca/sala de leitura.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2303, 6, 3, 'Os seguintes usuários da biblioteca (ou sala de leitura) levam livros para casa: Os membros da comunidade:', 74);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2303, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2303, 'B', 'Não, porque não querem');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2303, 'C', 'Não, porque a escola não permite');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2303, 'D', 'Não há biblioteca/sala de leitura.');
