INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2355, 6, 5, 'Qual é o seu sexo?', 1);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2355, 'A', 'Masculino.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2355, 'B', 'Feminino.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2356, 6, 5, 'Como você se considera?', 2);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2356, 'A', 'Branco(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2356, 'B', 'Pardo(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2356, 'C', 'Preto(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2356, 'D', 'Amarelo(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2356, 'E', 'Indígena.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2356, 'F', 'Não Sei.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2357, 6, 5, 'Você poderia nos dizer qual é o mês de seu aniversário?', 3);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2357, 'A', 'Janeiro.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2357, 'B', 'Fevereiro.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2357, 'C', 'Março.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2357, 'D', 'Abril.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2357, 'E', 'Maio.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2357, 'F', 'Junho.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2357, 'G', 'Julho.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2357, 'H', 'Agosto.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2357, 'I', 'Setembro.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2357, 'J', 'Outubro.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2357, 'K', 'Novembro.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2357, 'L', 'Dezembro.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2358, 6, 5, 'Em que ano você nasceu?', 4);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2358, 'A', '2001 ou depois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2358, 'B', '2000.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2358, 'C', '1999.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2358, 'D', '1998.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2358, 'E', '1997.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2358, 'F', '1996.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2358, 'G', '1995.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2358, 'H', '1994 ou antes.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2359, 6, 5, 'Na sua casa tem televisão em cores?', 5);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2359, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2359, 'B', 'Sim, uma.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2359, 'C', 'Sim, duas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2359, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2359, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2360, 6, 5, 'Na sua casa tem rádio?', 6);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2360, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2360, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2360, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2360, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2360, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2361, 6, 5, 'Na sua casa tem videocassete e/ou DVD?', 7);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2361, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2361, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2361, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2361, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2361, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2362, 6, 5, 'Na sua casa tem geladeira?', 8);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2362, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2362, 'B', 'Sim, uma.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2362, 'C', 'Sim, duas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2362, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2362, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2363, 6, 5, 'Na sua casa tem freezer (parte da geladeira duplex)?', 9);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2363, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2363, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2363, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2363, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2363, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2364, 6, 5, 'Na sua casa tem freezer separado da geladeira?', 10);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2364, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2364, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2364, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2364, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2364, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2365, 6, 5, 'Na sua casa tem máquina de lavar roupa (O tanquinho NÃO deve ser considerado)?', 11);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2365, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2365, 'B', 'Sim, uma.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2365, 'C', 'Sim, duas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2365, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2365, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2366, 6, 5, 'Na sua casa tem carro?', 12);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2366, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2366, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2366, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2366, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2366, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2367, 6, 5, 'Na sua casa tem computador?', 13);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2367, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2367, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2367, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2367, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2367, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2368, 6, 5, 'Na sua casa tem banheiro?', 14);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2368, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2368, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2368, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2368, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2368, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2369, 6, 5, 'Na sua casa tem quartos para dormir?', 15);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2369, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2369, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2369, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2369, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2369, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2370, 6, 5, 'Incluindo você, quantas pessoas vivem atualmente em sua casa?', 16);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2370, 'A', 'Uma, pois moro sozinho(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2370, 'B', 'Duas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2370, 'C', 'Três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2370, 'D', 'Quatro.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2370, 'E', 'Cinco.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2370, 'F', 'Seis pessoas ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2371, 6, 5, 'Em sua casa trabalha empregado(a) doméstico(a) pelo menos cinco dias por semana?', 17);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2371, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2371, 'B', 'Sim, um(a) empregado(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2371, 'C', 'Sim, dois(duas) empregados(as).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2371, 'D', 'Sim, três empregados(as).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2371, 'E', 'Sim, quatro ou mais empregados(as).');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2372, 6, 5, 'Você mora com sua mãe?', 18);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2372, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2372, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2372, 'C', 'Não, mas moro com outra mulher responsável por mim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2373, 6, 5, 'Até que série sua mãe, ou a mulher responsável por você, estudou?', 19);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2373, 'A', 'Nunca estudou.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2373, 'B', 'Não completou a 4.ª série/5.º ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2373, 'C', 'Completou a 4.ª série/5.º ano, mas não completou a 8.ª série/9.º ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2373, 'D', 'Completou a 8.ª série/9.º ano, mas não completou o Ensino Médio.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2373, 'E', 'Completou o Ensino Médio, mas não completou a Faculdade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2373, 'F', 'Completou a Faculdade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2373, 'G', 'Não sei.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2374, 6, 5, 'Sua mãe, ou a mulher responsável por você, sabe ler e escrever?', 20);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2374, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2374, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2375, 6, 5, 'Você vê sua mãe, ou mulher responsável por você, lendo?', 21);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2375, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2375, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2376, 6, 5, 'Você mora com seu pai?', 22);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2376, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2376, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2376, 'C', 'Não, mas moro com outro homem responsável por mim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2377, 6, 5, 'Até que série seu pai, ou o homem responsável por você, estudou?', 23);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2377, 'A', 'Nunca estudou.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2377, 'B', 'Não completou a 4.ª série/5.º ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2377, 'C', 'Completou a 4.ª série/5.º ano, mas não completou a 8.ª série/9.º ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2377, 'D', 'Completou a 8.ª série/9.º ano, mas não completou o Ensino Médio.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2377, 'E', 'Completou o Ensino Médio, mas não completou a Faculdade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2377, 'F', 'Completou a Faculdade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2377, 'G', 'Não sei.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2378, 6, 5, 'Seu pai, ou homem responsável por você, sabe ler e escrever?', 24);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2378, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2378, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2379, 6, 5, 'Você vê o seu pai, ou homem responsável por você, lendo?', 25);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2379, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2379, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2380, 6, 5, 'Com qual frequência seus pais, ou responsáveis por você, vão à reunião de pais?', 26);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2380, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2380, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2380, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2381, 6, 5, 'Seus pais ou responsáveis incentivam você a estudar?', 27);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2381, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2381, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2382, 6, 5, 'Seus pais ou responsáveis incentivam você a fazer o dever de casa e/ou os trabalhos da escola?', 28);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2382, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2382, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2383, 6, 5, 'Seus pais ou responsáveis incentivam você a ler?', 29);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2383, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2383, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2384, 6, 5, 'Seus pais ou responsáveis incentivam você a ir a escola e/ou não faltar às aulas?', 30);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2384, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2384, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2385, 6, 5, 'Seus pais ou responsáveis conversam com você sobre o que acontece na escola?', 31);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2385, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2385, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2386, 6, 5, 'Com qual frequência você lê: Jornais.', 32);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2386, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2386, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2386, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2387, 6, 5, 'Com qual frequência você lê: Livros em geral.', 33);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2387, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2387, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2387, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2388, 6, 5, 'Com qual frequência você lê: Livros de literatura.', 34);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2388, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2388, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2388, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2389, 6, 5, 'Com qual frequência você lê: Revistas em geral.', 35);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2389, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2389, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2389, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2390, 6, 5, 'Com qual frequência você lê: Revistas em quadrinhos (gibis).', 36);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2390, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2390, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2390, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2391, 6, 5, 'Com qual frequência você lê: Revistas de comportamento, celebridades, esportes ou TV.', 37);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2391, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2391, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2391, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2392, 6, 5, 'Com qual frequência você lê: Notícias na internet (ex.: blog, notícia).', 38);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2392, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2392, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2392, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2393, 6, 5, 'Com qual frequência você costuma ir à biblioteca?', 39);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2393, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2393, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2393, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2394, 6, 5, 'Com qual frequência você costuma ir ao cinema?', 40);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2394, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2394, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2394, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2395, 6, 5, 'Com qual frequência você costuma ir a algum tipo de espetáculo ou exposição (teatro, museu, dança, música)?', 41);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2395, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2395, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2395, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2396, 6, 5, 'Com qual frequência você participa de festas na sua vizinhaça ou comunidade?', 42);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2396, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2396, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2396, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2397, 6, 5, 'Em dia de aula, quanto tempo você gasta assistindo à TV, navegando na internet ou jogando jogos eletrônicos?', 43);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2397, 'A', 'Menos de 1 hora.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2397, 'B', 'Entre 1 e 2 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2397, 'C', 'Mais de 2 horas, até 3 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2397, 'D', 'Mais de 3 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2397, 'E', 'Não vejo TV, não navego na internet e não jogo jogos eletrônicos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2398, 6, 5, 'Em dias de aula, quanto tempo você gasta fazendo trabalhos domésticos (ex.: lavando louça, limpando o quintal etc.)?', 44);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2398, 'A', 'Menos de 1 hora.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2398, 'B', 'Entre 1 e 2 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2398, 'C', 'Mais de 2 horas, até 3 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2398, 'D', 'Mais de 3 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2398, 'E', 'Não faço trabalhos domésticos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2399, 6, 5, 'Atualmente você trabalha fora de casa (recebendo ou não um salário)?', 45);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2399, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2399, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2400, 6, 5, 'Quando você entrou na escola?', 46);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2400, 'A', 'Na creche (0 a 3 anos).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2400, 'B', 'Na pré-escola (4 a 5 anos).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2400, 'C', 'Na primeira série ou primeiro ano (6 a 7 anos).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2400, 'D', 'Depois da primeira série.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2401, 6, 5, 'A partir da quinta série ou sexto ano, em que tipo de escola você estudou?', 47);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2401, 'A', 'Somente em escola pública.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2401, 'B', 'Somente em escola particular.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2401, 'C', 'Em escola pública e em escola particular.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2402, 6, 5, 'Você já foi reprovado?', 48);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2402, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2402, 'B', 'Sim, uma vez.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2402, 'C', 'Sim, duas vezes ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2403, 6, 5, 'Você já abandonou a escola durante o período de aulas e ficou fora da escola o resto do ano?', 49);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2403, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2403, 'B', 'Sim, uma vez.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2403, 'C', 'Sim, duas vezes ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2404, 6, 5, 'Você gosta de estudar Língua Portuguesa?', 50);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2404, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2404, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2405, 6, 5, 'Você faz o dever de casa de Língua Portuguesa?', 51);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2405, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2405, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2405, 'C', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2405, 'D', 'O(A) professor(a) não passa dever de casa.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2406, 6, 5, 'O(A) professor(a) corrige o dever de casa de Língua Portuguesa?', 52);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2406, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2406, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2406, 'C', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2406, 'D', 'O(A) professor(a) não passa dever de casa.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2407, 6, 5, 'Você gosta de estudar Matemática?', 53);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2407, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2407, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2408, 6, 5, 'Você faz o dever de casa de Matemática?', 54);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2408, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2408, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2408, 'C', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2408, 'D', 'O(A) professor(a) não passa dever de casa.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2409, 6, 5, 'O(A) professor(a) corrige o dever de casa de Matemática?', 55);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2409, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2409, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2409, 'C', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2409, 'D', 'O(A) professor(a) não passa dever de casa.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2410, 6, 5, 'Você utiliza a biblioteca ou sala de leitura da sua escola?', 56);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2410, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2410, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2410, 'C', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2410, 'D', 'A escola não possui biblioteca ou sala de leitura.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2411, 6, 5, 'Quando você terminar o 9º ano(8ª série) você pretende:', 57);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2411, 'A', 'Somente continuar estudando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2411, 'B', 'Somente trabalhar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2411, 'C', 'Continuar estudando e trabalhar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2411, 'D', 'Ainda não sei.');
