INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2111, 6, 2, 'Qual é o seu sexo?', 1);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2111, 'A', 'Masculino.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2111, 'B', 'Feminino.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2112, 6, 2, 'Você poderia nos dizer a sua faixa etária?', 2);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2112, 'A', 'Até 24 anos');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2112, 'B', 'De 25 a 29 anos');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2112, 'C', 'De 30 a 39 anos');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2112, 'D', 'De 40 a 49 anos');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2112, 'E', 'De 50 a 54 anos');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2112, 'F', '55 anos ou mais');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2113, 6, 2, 'Como você se considera?', 3);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2113, 'A', 'Branco (a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2113, 'B', 'Pardo (a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2113, 'C', 'Preto (a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2113, 'D', 'Amarelo (a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2113, 'E', 'Indígena.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2113, 'F', 'Não quero declarar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2113, 'G', 'Não sei.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2114, 6, 2, 'Qual é o mais alto nível de escolaridade que você concluiu (até a graduação)?', 4);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2114, 'A', 'Menos que o Ensino Médio (antigo 2º grau).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2114, 'B', 'Ensino Médio - Magistério (antigo 2º grau).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2114, 'C', 'Ensino  Médio - Outros (antigo 2º grau).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2114, 'D', 'Ensino Superior - Pedagogia.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2114, 'E', 'Ensino Superior - Curso Normal Superior.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2114, 'F', 'Ensino Superior - Licenciatura em Matemática.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2114, 'G', 'Ensino Superior - Licenciatura em Letras.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2114, 'H', 'Ensino Superior – Outras Licenciaturas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2114, 'I', 'Ensino Superior - Outras áreas.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2115, 6, 2, 'Há quantos anos você obteve o nível de escolaridade assinalado anteriormente (até a graduação)?', 5);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2115, 'A', 'Há menos de 2 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2115, 'B', 'De 2 a 7 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2115, 'C', 'De 8 a 14 anos');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2115, 'D', 'De 15 a 20 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2115, 'E', 'Há mais de 20 anos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2116, 6, 2, 'Indique em que tipo de instituição você obteve seu diploma de ensino superior.', 6);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2116, 'A', 'Não concluí o ensino superior.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2116, 'B', 'Privada.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2116, 'C', 'Pública Federal.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2116, 'D', 'Pública Estadual.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2116, 'E', 'Pública Municipal.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2117, 6, 2, 'De que forma você realizou o curso de ensino superior?', 7);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2117, 'A', 'Não concluí o ensino superior.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2117, 'B', 'Presencial.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2117, 'C', 'Semipresencial.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2117, 'D', 'A distância.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2118, 6, 2, 'Indique o curso de pós-graduação de mais alta titulação que você possui.', 8);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2118, 'A', 'Não fiz ou não completei curso de pós-graduação.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2118, 'B', 'Atualização ou Aperfeiçoamento (mínimo de 180 horas).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2118, 'C', 'Especialização (mínimo de 360 horas).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2118, 'D', 'Mestrado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2118, 'E', 'Doutorado.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2119, 6, 2, 'Indique a área temática do curso de pós-graduação de mais alta titulação que você possui.', 9);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2119, 'A', 'Não fiz ou não completei curso de pós-graduação.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2119, 'B', 'Educação, enfatizando alfabetização.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2119, 'C', 'Educação, enfatizando linguística e/ou letramento.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2119, 'D', 'Educação, enfatizando educação matemática.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2119, 'E', 'Educação - outras ênfases.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2119, 'F', 'Outras áreas que não a Educação.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2120, 6, 2, 'Como professor, qual é, aproximadamente, o seu salário bruto? (com adicionais, se houver).', 10);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2120, 'A', 'Até R$ 678,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2120, 'B', 'Entre R$ 679,00 e R$ 1.017,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2120, 'C', 'Entre R$ 1.018,00 e R$ 1.356,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2120, 'D', 'Entre R$ 1.357,00 e R$ 1.695,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2120, 'E', 'Entre R$ 1.696,00 e R$ 2.034,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2120, 'F', 'Entre R$ 2.035,00 e R$ 2.373,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2120, 'G', 'Entre R$ 2.374,00 e R$ 2.712,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2120, 'H', 'Entre R$ 2.713,00 e R$ 3.390,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2120, 'I', 'Entre R$ 3.391,00 e R$ 4.746,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2120, 'J', 'Entre R$ 4.747,00 e R$ 6.780,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2120, 'K', 'R$ 6.781,00 ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2121, 6, 2, 'Além da atividade como docente nesta escola, você exerce outra atividade que contribui para sua renda pessoal?', 11);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2121, 'A', 'Sim, na área de educação.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2121, 'B', 'Sim, fora da área de educação.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2121, 'C', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2122, 6, 2, 'Considerando todas as atividades que você exerce (dentro e fora da área de educação), qual é, aproximadamente, o seu salário bruto? (com adicionais, se houver).', 12);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2122, 'A', 'Até R$ 678,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2122, 'B', 'Entre R$ 679,00 e R$ 1.017,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2122, 'C', 'Entre R$ 1.018,00 e R$ 1.356,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2122, 'D', 'Entre R$ 1.357,00 e R$ 1.695,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2122, 'E', 'Entre R$ 1.696,00 e R$ 2.034,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2122, 'F', 'Entre R$ 2.035,00 e R$ 2.373,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2122, 'G', 'Entre R$ 2.374,00 e R$ 2.712,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2122, 'H', 'Entre R$ 2.713,00 e R$ 3.390,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2122, 'I', 'Entre R$ 3.391,00 e R$ 4.746,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2122, 'J', 'Entre R$ 4.747,00 e R$ 6.780,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2122, 'K', 'R$ 6.781,00 ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2123, 6, 2, 'Há quantos anos você trabalha como professor?', 13);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2123, 'A', 'Meu primeiro ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2123, 'B', '1-2 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2123, 'C', '3-5 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2123, 'D', '6-10 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2123, 'E', '11-15 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2123, 'F', '16-20 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2123, 'G', 'Mais de 20 anos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2124, 6, 2, 'Há quantos anos você trabalha como professor nesta escola?', 14);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2124, 'A', 'Meu primeiro ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2124, 'B', '1-2 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2124, 'C', '3-5 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2124, 'D', '6-10 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2124, 'E', '11-15 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2124, 'F', '16-20 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2124, 'G', 'Mais de 20 anos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2125, 6, 2, 'Há quantos anos você ministra aulas para alunos da série/turma em que você se encontra neste momento?', 15);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2125, 'A', 'Meu primeiro ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2125, 'B', '1-2 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2125, 'C', '3-5 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2125, 'D', '6-10 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2125, 'E', '11-15 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2125, 'F', '16-20 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2125, 'G', 'Mais de 20 anos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2126, 6, 2, 'Qual é a sua situação trabalhista nesta escola?', 16);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2126, 'A', 'Estatutário.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2126, 'B', 'CLT.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2126, 'C', 'Prestador de serviço por contrato temporário.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2126, 'D', 'Prestador de serviço sem contrato.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2126, 'E', 'Outra.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2127, 6, 2, 'Nesta escola, qual a sua carga horária semanal? (Considere a carga horária contratual: horas-aula mais horas para atividades, se houver. Não considere aulas particulares)', 17);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2127, 'A', 'Mais de 40 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2127, 'B', '40 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2127, 'C', 'De 20 a 39 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2127, 'D', 'Menos de 20 horas.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2128, 6, 2, 'Em quantas escolas você trabalha?', 18);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2128, 'A', 'Apenas nesta escola.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2128, 'B', 'Em 2 escolas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2128, 'C', 'Em 3 escolas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2128, 'D', 'Em 4 ou mais escolas.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2129, 6, 2, 'Considerando todas as escolas em que você trabalha atualmente como professor, qual a sua carga horária semanal? (Considere a carga horária contratual: horas-aula mais horas para atividades, se houver. Não considere aulas particulares)', 19);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2129, 'A', 'Mais de 40 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2129, 'B', '40 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2129, 'C', 'De 20 a 39 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2129, 'D', 'Menos de 20 horas.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2130, 6, 2, 'Considerando-se todas as escolas em que você trabalha atualmente como professor, quantas horas semanais são dedicadas às atividades extraclasse (formação e estudo, planejamento, produção de recursos didáticos etc.)?', 20);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2130, 'A', 'Nenhuma');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2130, 'B', 'Menos de 1/3 da carga horária.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2130, 'C', '1/3 da carga horária.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2130, 'D', 'Mais de 1/3 da carga horária.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2131, 6, 2, 'Durante os últimos dois anos, você participou de qualquer um dos seguintes tipos de atividades de desenvolvimento profissional, e qual foi o impacto dessa atividade em sua prática como professor? Cursos/oficinas sobre metodologias de ensino na sua área de atuação.', 21);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2131, 'A', 'Não participei.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2131, 'B', 'Sim, e não houve impacto.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2131, 'C', 'Sim, e houve um pequeno impacto.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2131, 'D', 'Sim, e houve um impacto moderado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2131, 'E', 'Sim, e houve um grande impacto.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2132, 6, 2, 'Durante os últimos dois anos, você participou de qualquer um dos seguintes tipos de atividades de desenvolvimento profissional, e qual foi o impacto dessa atividade em sua prática como professor? Cursos/oficinas sobre outros tópicos em educação.', 22);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2132, 'A', 'Não participei.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2132, 'B', 'Sim, e não houve impacto.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2132, 'C', 'Sim, e houve um pequeno impacto.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2132, 'D', 'Sim, e houve um impacto moderado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2132, 'E', 'Sim, e houve um grande impacto.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2133, 6, 2, 'Durante os últimos dois anos, você participou de qualquer um dos seguintes tipos de atividades de desenvolvimento profissional, e qual foi o impacto dessa atividade em sua prática como professor? Curso de especialização (mínimo de 360 horas) ou aperfeiçoamento (mínimo de 180 horas) sobre metodologias de ensino na sua área de atuação.', 23);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2133, 'A', 'Não participei.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2133, 'B', 'Sim, e não houve impacto.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2133, 'C', 'Sim, e houve um pequeno impacto.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2133, 'D', 'Sim, e houve um impacto moderado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2133, 'E', 'Sim, e houve um grande impacto.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2134, 6, 2, 'Durante os últimos dois anos, você participou de qualquer um dos seguintes tipos de atividades de desenvolvimento profissional, e qual foi o impacto dessa atividade em sua prática como professor? Curso de especialização (mínimo de 360 horas) ou aperfeiçoamento (mínimo 180 horas) sobre outros tópicos em educação.', 24);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2134, 'A', 'Não participei.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2134, 'B', 'Sim, e não houve impacto.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2134, 'C', 'Sim, e houve um pequeno impacto.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2134, 'D', 'Sim, e houve um impacto moderado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2134, 'E', 'Sim, e houve um grande impacto.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2135, 6, 2, 'Das atividades de desenvolvimento profissional de que você participou nos últimos dois anos, quantas você, pessoalmente, teve que pagar para participar?', 25);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2135, 'A', 'Nenhuma');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2135, 'B', 'Algumas');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2135, 'C', 'Todas');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2136, 6, 2, 'Considerando os temas a seguir, indique por favor sua necessidade de aperfeiçoamento profissional. Parâmetros ou Diretrizes curriculares em sua área de atuação.', 26);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2136, 'A', 'Não há necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2136, 'B', 'Baixo nível de necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2136, 'C', 'Nível moderado de necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2136, 'D', 'Alto nível de necessidade.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2137, 6, 2, 'Considerando os temas a seguir, indique por favor sua necessidade de aperfeiçoamento profissional. Conteúdos específicos da minha disciplina principal de atuação.', 27);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2137, 'A', 'Não há necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2137, 'B', 'Baixo nível de necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2137, 'C', 'Nível moderado de necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2137, 'D', 'Alto nível de necessidade.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2138, 6, 2, 'Considerando os temas a seguir, indique por favor sua necessidade de aperfeiçoamento profissional. Práticas de Ensino na minha disciplina principal de atuação.', 28);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2138, 'A', 'Não há necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2138, 'B', 'Baixo nível de necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2138, 'C', 'Nível moderado de necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2138, 'D', 'Alto nível de necessidade.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2139, 6, 2, 'Considerando os temas a seguir, indique por favor sua necessidade de aperfeiçoamento profissional. Gestão e organização das atividades em sala de aula.', 29);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2139, 'A', 'Não há necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2139, 'B', 'Baixo nível de necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2139, 'C', 'Nível moderado de necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2139, 'D', 'Alto nível de necessidade.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2140, 6, 2, 'Considerando os temas a seguir, indique por favor sua necessidade de aperfeiçoamento profissional. Metodologias de avaliação dos alunos.', 30);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2140, 'A', 'Não há necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2140, 'B', 'Baixo nível de necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2140, 'C', 'Nível moderado de necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2140, 'D', 'Alto nível de necessidade.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2141, 6, 2, 'Considerando os temas a seguir, indique por favor sua necessidade de aperfeiçoamento profissional. Uso pedagógico das Tecnologias de Informação e Comunicação.', 31);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2141, 'A', 'Não há necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2141, 'B', 'Baixo nível de necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2141, 'C', 'Nível moderado de necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2141, 'D', 'Alto nível de necessidade.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2142, 6, 2, 'Considerando os temas a seguir, indique por favor sua necessidade de aperfeiçoamento profissional. Formação específica para trabalhar com estudantes com deficiência ou
necessidades especiais.Considerando os temas a seguir, indique por favor sua necessidade de aperfeiçoamento profissional. Formação específica para trabalhar com estudantes com deficiência ou
necessidades especiais.Considerando os temas a seguir, indique por favor sua necessidade de aperfeiçoamento profissional. Formação específica para trabalhar com estudantes com deficiência ou
necessidades especiais.Considerando os temas a seguir, indique por favor sua necessidade de aperfeiçoamento profissional. Formação específica para trabalhar com estudantes com deficiência ou
necessidades especiais.Considerando os temas a seguir, indique por favor sua necessidade de aperfeiçoamento profissional. Formação específica para trabalhar com estudantes com deficiência ou
necessidades especiais.Considerando os temas a seguir, indique por favor sua necessidade de aperfeiçoamento profissional. Formação específica para trabalhar com estudantes com deficiência ou
necessidades especiais.Considerando os temas a seguir, indique por favor sua necessidade de aperfeiçoamento profissional. Formação específica para trabalhar com estudantes com deficiência ou
necessidades especiais.', 32);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2142, 'A', 'Não há necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2142, 'B', 'Baixo nível de necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2142, 'C', 'Nível moderado de necessidade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2142, 'D', 'Alto nível de necessidade.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2143, 6, 2, 'Nos últimos dois anos, você gostaria de ter  participado de mais atividades de desenvolvimento profissional do que você participou?', 33);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2143, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2143, 'B', 'Sim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2144, 6, 2, 'Se você gostaria de ter participado de mais atividades de desenvolvimento profissional, os seguintes motivos impediram sua participação? O desenvolvimento profissional era muito caro/eu não podia pagar.', 34);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2144, 'A', 'Não gostaria de ter participado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2144, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2144, 'C', 'Sim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2145, 6, 2, 'Se você gostaria de ter participado de mais atividades de desenvolvimento profissional, os seguintes motivos impediram sua participação? Houve conflito com o meu horário de trabalho.', 35);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2145, 'A', 'Não gostaria de ter participado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2145, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2145, 'C', 'Sim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2146, 6, 2, 'Se você gostaria de ter participado de mais atividades de desenvolvimento profissional, os seguintes motivos impediram sua participação? Não tinha disponibilidade de tempo.', 36);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2146, 'A', 'Não gostaria de ter participado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2146, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2146, 'C', 'Sim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2147, 6, 2, 'Se você gostaria de ter participado de mais atividades de desenvolvimento profissional, os seguintes motivos impediram sua participação? Não houve oferta em minha área de interesse.', 37);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2147, 'A', 'Não gostaria de ter participado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2147, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2147, 'C', 'Sim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2148, 6, 2, 'Em seu tempo livre, você costuma: Ler jornais e revistas em geral.', 38);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2148, 'A', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2148, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2148, 'C', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2149, 6, 2, 'Em seu tempo livre, você costuma: Ler livros.', 39);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2149, 'A', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2149, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2149, 'C', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2150, 6, 2, 'Em seu tempo livre, você costuma: Ler sites na internet.', 40);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2150, 'A', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2150, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2150, 'C', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2151, 6, 2, 'Em seu tempo livre, você costuma: Frequentar bibliotecas.', 41);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2151, 'A', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2151, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2151, 'C', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2152, 6, 2, 'Em seu tempo livre, você costuma: Ir ao cinema.', 42);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2152, 'A', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2152, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2152, 'C', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2153, 6, 2, 'Em seu tempo livre, você costuma: Ir a algum tipo de espetáculo ou exposição (teatro, museu, dança, música).', 43);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2153, 'A', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2153, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2153, 'C', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2154, 6, 2, 'Gostaríamos de saber quais os recursos que você utiliza para fins pedagógicos, nesta turma: Jornais e revistas informativas.', 44);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2154, 'A', 'Não utilizo porque a escola não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2154, 'B', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2154, 'C', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2154, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2155, 6, 2, 'Gostaríamos de saber quais os recursos que você utiliza para fins pedagógicos, nesta turma: Livros de literatura em geral.', 45);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2155, 'A', 'Não utilizo porque a escola não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2155, 'B', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2155, 'C', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2155, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2156, 6, 2, 'Gostaríamos de saber quais os recursos que você utiliza para fins pedagógicos, nesta turma: Projetor (datashow, projetor de transparências).', 46);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2156, 'A', 'Não utilizo porque a escola não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2156, 'B', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2156, 'C', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2156, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2157, 6, 2, 'Gostaríamos de saber quais os recursos que você utiliza para fins pedagógicos, nesta turma: Filmes, desenhos animados ou documentários.', 47);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2157, 'A', 'Não utilizo porque a escola não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2157, 'B', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2157, 'C', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2157, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2158, 6, 2, 'Gostaríamos de saber quais os recursos que você utiliza para fins pedagógicos, nesta turma: Máquina copiadora (xerox).', 48);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2158, 'A', 'Não utilizo porque a escola não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2158, 'B', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2158, 'C', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2158, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2159, 6, 2, 'Gostaríamos de saber quais os recursos que você utiliza para fins pedagógicos, nesta turma: Programas/aplicativos pedagógicos de computador.', 49);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2159, 'A', 'Não utilizo porque a escola não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2159, 'B', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2159, 'C', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2159, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2160, 6, 2, 'Gostaríamos de saber quais os recursos que você utiliza para fins pedagógicos, nesta turma: Internet.', 50);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2160, 'A', 'Não utilizo porque a escola não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2160, 'B', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2160, 'C', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2160, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2161, 6, 2, 'Neste ano e nesta escola, como se deu a elaboração do Projeto Pedagógico?', 51);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2161, 'A', 'Não sei como foi desenvolvido.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2161, 'B', 'Não existe Projeto Pedagógico.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2161, 'C', 'Utilizando-se um modelo pronto, sem discussão com a equipe escolar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2161, 'D', 'Utilizando-se um modelo pronto, mas com discussão com a equipe escolar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2161, 'E', 'Utilizando-se um modelo pronto, porém com adaptações, sem discussão com a equipe escolar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2161, 'F', 'Utilizando-se um modelo pronto, porém com adaptações e com discussão com a equipe escolar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2161, 'G', 'Elaborou-se um modelo próprio, mas não houve discussão com a equipe escolar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2161, 'H', 'Elaborou-se um modelo próprio e houve discussão com a equipe escolar.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2162, 6, 2, 'O Conselho de Classe é um órgão formado por todos os professores que lecionam em cada turma/série. Neste ano e nesta escola, quantas vezes se reuniu o Conselho de Classe?', 52);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2162, 'A', 'Não existe Conselho de Classe nesta escola.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2162, 'B', 'Nenhuma vez.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2162, 'C', 'Uma vez.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2162, 'D', 'Duas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2162, 'E', 'Três vezes ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2163, 6, 2, 'Nesta escola, com que frequência você fezo seguinte: Participou do planejamento do currículo escolar ou parte dele.', 53);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2163, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2163, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2163, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2163, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2163, 'E', 'Semanalmente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2164, 6, 2, 'Nesta escola, com que frequência você fezo seguinte: Trocou materiais didáticos com seus colegas.', 54);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2164, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2164, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2164, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2164, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2164, 'E', 'Semanalmente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2165, 6, 2, 'Nesta escola, com que frequência você fezo seguinte: Participou de reuniões com colegas que trabalham com a mesma série (ano) para a(o) qual leciona.', 55);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2165, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2165, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2165, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2165, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2165, 'E', 'Semanalmente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2166, 6, 2, 'Nesta escola, com que frequência você fezo seguinte: Participou em discussões sobre o desenvolvimento da aprendizagem de determinados alunos.', 56);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2166, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2166, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2166, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2166, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2166, 'E', 'Semanalmente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2167, 6, 2, 'Nesta escola, com que frequência você fezo seguinte: Envolveu-se em atividades conjuntas com diferentes professores (por exemplo, projetos interdisciplinares).', 57);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2167, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2167, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2167, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2167, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2167, 'E', 'Semanalmente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2168, 6, 2, 'Nesta escola e neste ano, indique a frequência com que: O(A) diretor(a) discute metas educacionais com os professores nas reuniões.', 58);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2168, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2168, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2168, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2168, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2169, 6, 2, 'Nesta escola e neste ano, indique a frequência com que: O(A) diretor(a) e os professores procuram assegurar que as questões de qualidade de ensino sejam uma responsabilidade coletiva.', 59);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2169, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2169, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2169, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2169, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2170, 6, 2, 'Nesta escola e neste ano, indique a frequência com que: O(A) diretor(a) informa os professores sobre as possibilidades de aperfeiçoamento profissional.', 60);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2170, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2170, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2170, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2170, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2171, 6, 2, 'Nesta escola e neste ano, indique a frequência com que: O(A) diretor(a) dá atenção especial a aspectos relacionados com a aprendizagem dos alunos.', 61);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2171, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2171, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2171, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2171, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2172, 6, 2, 'Nesta escola e neste ano, indique a frequência com que: O(A) diretor(a) dá atenção especial a aspectos relacionados com as normas administrativas.', 62);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2172, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2172, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2172, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2172, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2173, 6, 2, 'Nesta escola e neste ano, indique a frequência com que: O(A) diretor(a) dá atenção especial a aspectos relacionados com a manutenção da escola.', 63);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2173, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2173, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2173, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2173, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2174, 6, 2, 'Nesta escola e neste ano, indique a frequência com que: O(A) diretor(a) me anima e me motiva para o trabalho.', 64);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2174, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2174, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2174, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2174, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2175, 6, 2, 'Nesta escola e neste ano, indique a frequência com que: O(A) diretor(a) estimula atividades inovadoras.', 65);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2175, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2175, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2175, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2175, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2176, 6, 2, 'Nesta escola e neste ano, indique a frequência com que: Sinto-me respeitado pelo(a) diretor(a).', 66);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2176, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2176, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2176, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2176, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2177, 6, 2, 'Nesta escola e neste ano, indique a frequência com que: Tenho confiança no(a) diretor(a) como profissional.', 67);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2177, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2177, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2177, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2177, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2178, 6, 2, 'Nesta escola e neste ano, indique a frequência com que: Participo das decisões relacionadas com meu trabalho.', 68);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2178, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2178, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2178, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2178, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2179, 6, 2, 'Nesta escola e neste ano, indique a frequência com que: A equipe de professores leva em consideração minhas ideias.', 69);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2179, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2179, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2179, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2179, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2180, 6, 2, 'Na sua percepção, os possíveis problemas de aprendizagem dos alunos das série(s) ou ano(s) avaliado(s) ocorrem, nesta escola, devido à/ao(s): Carência de infraestrutura física.', 70);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2180, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2180, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2181, 6, 2, 'Na sua percepção, os possíveis problemas de aprendizagem dos alunos das série(s) ou ano(s) avaliado(s) ocorrem, nesta escola, devido à/ao(s): Carência ou ineficiência da supervisão, coordenação e orientação pedagógica.', 71);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2181, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2181, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2182, 6, 2, 'Na sua percepção, os possíveis problemas de aprendizagem dos alunos das série(s) ou ano(s) avaliado(s) ocorrem, nesta escola, devido à/ao(s): Conteúdos curriculares inadequados às necessidades dos alunos.', 72);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2182, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2182, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2183, 6, 2, 'Na sua percepção, os possíveis problemas de aprendizagem dos alunos das série(s) ou ano(s) avaliado(s) ocorrem, nesta escola, devido à/ao(s): Não cumprimento dos conteúdos curriculares ao longo da trajetória escolar do aluno.', 73);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2183, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2183, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2184, 6, 2, 'Na sua percepção, os possíveis problemas de aprendizagem dos alunos das série(s) ou ano(s) avaliado(s) ocorrem, nesta escola, devido à/ao(s): Sobrecarga de trabalho dos professores, dificultando o planejamento e o preparo das aulas.', 74);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2184, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2184, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2185, 6, 2, 'Na sua percepção, os possíveis problemas de aprendizagem dos alunos das série(s) ou ano(s) avaliado(s) ocorrem, nesta escola, devido à/ao(s): Insatisfação e desestímulo do professor com a carreira docente.', 75);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2185, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2185, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2186, 6, 2, 'Na sua percepção, os possíveis problemas de aprendizagem dos alunos das série(s) ou ano(s) avaliado(s) ocorrem, nesta escola, devido à/ao(s): Meio social em que o aluno vive.', 76);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2186, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2186, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2187, 6, 2, 'Na sua percepção, os possíveis problemas de aprendizagem dos alunos das série(s) ou ano(s) avaliado(s) ocorrem, nesta escola, devido à/ao(s): Nível cultural dos pais dos alunos.', 77);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2187, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2187, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2188, 6, 2, 'Na sua percepção, os possíveis problemas de aprendizagem dos alunos das série(s) ou ano(s) avaliado(s) ocorrem, nesta escola, devido à/ao(s): Falta de assistência e acompanhamento dos pais na vida escolar do aluno.', 78);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2188, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2188, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2189, 6, 2, 'Na sua percepção, os possíveis problemas de aprendizagem dos alunos das série(s) ou ano(s) avaliado(s) ocorrem, nesta escola, devido à/ao(s): Baixa autoestima dos alunos.', 79);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2189, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2189, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2190, 6, 2, 'Na sua percepção, os possíveis problemas de aprendizagem dos alunos das série(s) ou ano(s) avaliado(s) ocorrem, nesta escola, devido à/ao(s): Desinteresse e falta de esforço do aluno.', 80);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2190, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2190, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2191, 6, 2, 'Na sua percepção, os possíveis problemas de aprendizagem dos alunos das série(s) ou ano(s) avaliado(s) ocorrem, nesta escola, devido à/ao(s): Indisciplina dos alunos em sala de aula.', 81);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2191, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2191, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2192, 6, 2, 'Na sua percepção, os possíveis problemas de aprendizagem dos alunos das série(s) ou ano(s) avaliado(s) ocorrem, nesta escola, devido à/ao(s): Alto índice de faltas por parte dos alunos.', 82);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2192, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2192, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2193, 6, 2, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não neste ano, nesta escola: Agressão verbal ou física de alunos a professores ou a funcionários da escola.', 83);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2193, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2193, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2194, 6, 2, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não neste ano, nesta escola: Agressão verbal ou física de alunos a outros alunos da escola.', 84);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2194, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2194, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2195, 6, 2, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não neste ano, nesta escola: Você foi vítima de atentado à vida.', 85);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2195, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2195, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2196, 6, 2, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não neste ano, nesta escola: Você foi ameaçado por algum aluno.', 86);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2196, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2196, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2197, 6, 2, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não neste ano, nesta escola: Você foi vítima de furto (sem uso de violência).', 87);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2197, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2197, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2198, 6, 2, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não neste ano, nesta escola: Você foi vítima de roubo (com uso de violência).', 88);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2198, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2198, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2199, 6, 2, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não neste ano, nesta escola: Alunos frequentaram as suas aulas sob efeito de bebida alcoólica.', 89);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2199, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2199, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2200, 6, 2, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não neste ano, nesta escola: Alunos frequentaram as suas aulas sob efeito de drogas ilícitas.', 90);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2200, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2200, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2201, 6, 2, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não neste ano, nesta escola: Alunos frequentaram as suas aulas portando arma branca (facas, canivetes etc.).', 91);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2201, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2201, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2202, 6, 2, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não neste ano, nesta escola: Alunos frequentaram as suas aulas portando arma de fogo.', 92);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2202, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2202, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2203, 6, 2, '(SOMENTE PARA PROFESSORES DA 4.ª série/5.º ano) Na sua opinião, quantos dos alunos desta turma você acha que concluirão a 4.ª série/5.º ano neste ano?', 93);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2203, 'A', 'Poucos alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2203, 'B', 'Um pouco menos da metade dos alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2203, 'C', 'Um pouco mais da metade dos alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2203, 'D', 'Quase todos os alunos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2204, 6, 2, '(SOMENTE PARA PROFESSORES DA 4.ª série/5.º ano e 8.ª série/9.º ano) Na sua opinião, quantos dos alunos desta turma você acha que concluirão o ensino fundamental?', 94);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2204, 'A', 'Poucos alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2204, 'B', 'Um pouco menos da metade dos alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2204, 'C', 'Um pouco mais da metade dos alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2204, 'D', 'Quase todos os alunos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2205, 6, 2, '(PARA TODOS OS PROFESSORES) Quantos dos alunos desta turma você acha que concluirão o ensino médio?', 95);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2205, 'A', 'Poucos alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2205, 'B', 'Um pouco menos da metade dos alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2205, 'C', 'Um pouco mais da metade dos alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2205, 'D', 'Quase todos os alunos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2206, 6, 2, '(PARA TODOS OS PROFESSORES) Quantos dos alunos desta turma você acha que entrarão na universidade?', 96);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2206, 'A', 'Poucos alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2206, 'B', 'Um pouco menos da metade dos alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2206, 'C', 'Um pouco mais da metade dos alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2206, 'D', 'Quase todos os alunos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2207, 6, 2, 'Para a disciplina que você ministra neste ano, você participou da escolha dos livros didáticos para utilização nesta turma?', 97);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2207, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2207, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2208, 6, 2, 'O livro didático escolhido foi o recebido?', 98);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2208, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2208, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2208, 'C', 'Não sei.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2209, 6, 2, 'Os alunos desta turma têm livros didáticos?', 99);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2209, 'A', 'Não, esta turma não recebeu o livro didático.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2209, 'B', 'Sim, menos da metade da turma tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2209, 'C', 'Sim, metade da turma tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2209, 'D', 'Sim, a maioria tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2209, 'E', 'Sim, todos têm.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2210, 6, 2, 'Os alunos desta turma receberam o livro didático no início do ano letivo?', 100);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2210, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2210, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2210, 'C', 'Não sei.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2211, 6, 2, 'Como você avalia a qualidade dos livros didáticos que você utiliza nesta turma, neste ano?', 101);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2211, 'A', 'Não utilizo livros didáticos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2211, 'B', 'Ruim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2211, 'C', 'Razoável.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2211, 'D', 'Boa.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2211, 'E', 'Ótima.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2212, 6, 2, 'Para esta turma, qual o percentual do tempo de aula que você usualmente gastou realizando cada uma das seguintes atividades: Realizando tarefas administrativas (ex.: fazendo  a chamada, preenchendo formulários etc.)', 102);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2212, 'A', 'Menos de 10%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2212, 'B', 'De 10% a menos de 20%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2212, 'C', 'De 20% a menos de 40%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2212, 'D', 'De 40% a menos de 60%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2212, 'E', 'De 60% a menos de 80%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2212, 'F', '80% ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2213, 6, 2, 'Para esta turma, qual o percentual do tempo de aula que você usualmente gastou realizando cada uma das seguintes atividades: Mantendo a ordem/disciplina na sala de aula.', 103);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2213, 'A', 'Menos de 10%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2213, 'B', 'De 10% a menos de 20%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2213, 'C', 'De 20% a menos de 40%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2213, 'D', 'De 40% a menos de 60%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2213, 'E', 'De 60% a menos de 80%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2213, 'F', '80% ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2214, 6, 2, 'Para esta turma, qual o percentual do tempo de aula que você usualmente gastou realizando cada uma das seguintes atividades: Realizando atividades de ensino e aprendizagem.', 104);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2214, 'A', 'Menos de 10%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2214, 'B', 'De 10% a menos de 20%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2214, 'C', 'De 20% a menos de 40%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2214, 'D', 'De 40% a menos de 60%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2214, 'E', 'De 60% a menos de 80%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2214, 'F', '80% ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2215, 6, 2, 'Nesta turma, qual disciplina você leciona?', 105);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2215, 'A', 'Língua Portuguesa.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2215, 'B', 'Matemática.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2215, 'C', 'Mais de uma disciplina.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2216, 6, 2, 'Quanto do conteúdo previsto você conseguiu desenvolver com os alunos desta turma neste ano?', 106);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2216, 'A', 'Menos de 20%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2216, 'B', 'De 20% a menos de 40%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2216, 'C', 'De 40% a menos de 60%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2216, 'D', 'De 60% a menos de 80%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2216, 'E', '80% ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2217, 6, 2, 'Indique a frequência com que você desenvolve as seguintes práticas pedagógicas nesta turma: Propor dever de casa.', 107);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2217, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2217, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2217, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2217, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2217, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2217, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2218, 6, 2, 'Indique a frequência com que você desenvolve as seguintes práticas pedagógicas nesta turma: Corrigir com os alunos o dever de casa.', 108);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2218, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2218, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2218, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2218, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2218, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2218, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2219, 6, 2, 'Indique a frequência com que você desenvolve as seguintes práticas pedagógicas nesta turma: Desenvolver atividades em grupo, em sala de aula, para que os alunos busquem soluções de problemas.', 109);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2219, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2219, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2219, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2219, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2219, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2219, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2220, 6, 2, 'Indique a frequência com que você desenvolve as seguintes práticas pedagógicas nesta turma: Desenvolver projetos temáticos com o objetivo de aprimorar as habilidades de trabalho em equipe.', 110);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2220, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2220, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2220, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2220, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2220, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2220, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2221, 6, 2, 'Indique a frequência com que você desenvolve as seguintes práticas pedagógicas nesta turma: Solicitar que os alunos copiem textos e atividades do livro didático ou do quadro negro (lousa).', 111);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2221, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2221, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2221, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2221, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2221, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2221, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2222, 6, 2, 'Indique a frequência com que você desenvolve as seguintes práticas pedagógicas nesta turma: Estimular os alunos a expressarem suas opiniões e a desenvolverem argumentos a partir de temas diversos.', 112);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2222, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2222, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2222, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2222, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2222, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2222, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2223, 6, 2, 'Indique a frequência com que você desenvolve as seguintes práticas pedagógicas nesta turma: Propor situações de aprendizagem que sejam familiares ou de interesse dos alunos.', 113);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2223, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2223, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2223, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2223, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2223, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2223, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2224, 6, 2, 'Indique a frequência com que você desenvolve as seguintes práticas pedagógicas nesta turma: Promover discussões a partir de textos de jornais ou revistas.', 114);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2224, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2224, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2224, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2224, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2224, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2224, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2225, 6, 2, 'Indique a frequência com que você desenvolve as seguintes práticas pedagógicas nesta turma: Propor atividades gramaticais relacionadas aos textos de jornais ou revistas.', 115);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2225, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2225, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2225, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2225, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2225, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2225, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2226, 6, 2, 'Indique a frequência com que você desenvolve as seguintes práticas pedagógicas nesta turma: Promover a leitura e discussão de contos, crônicas, poesias ou romances.', 116);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2226, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2226, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2226, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2226, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2226, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2226, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2227, 6, 2, 'Indique a frequência com que você desenvolve as seguintes práticas pedagógicas nesta turma: Utilizar contos, crônicas, poesias ou romances para exercitar aspectos da gramática.', 117);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2227, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2227, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2227, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2227, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2227, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2227, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2228, 6, 2, 'Indique a frequência com que você desenvolve as seguintes práticas pedagógicas nesta turma: Utilizar revistas em quadrinhos como instrumento de aprendizado.', 118);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2228, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2228, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2228, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2228, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2228, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2228, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2229, 6, 2, 'Indique a frequência com que você desenvolve as seguintes práticas pedagógicas nesta turma: Fixar os nomes de conceitos gramaticais e linguísticos.', 119);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2229, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2229, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2229, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2229, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2229, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2229, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2230, 6, 2, 'Indique a frequência com a que você desenvolve as seguintes práticas pedagógicas nesta turma: Fazer exercícios para fixar procedimentos e regras.', 120);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2230, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2230, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2230, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2230, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2230, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2230, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2231, 6, 2, 'Indique a frequência com a que você desenvolve as seguintes práticas pedagógicas nesta turma: Discutir se os resultados numéricos obtidos na solução de um problema são adequados à situação apresentada.', 121);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2231, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2231, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2231, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2231, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2231, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2231, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2232, 6, 2, 'Indique a frequência com a que você desenvolve as seguintes práticas pedagógicas nesta turma: Discutir diferentes modos para resolver problemas e cálculos.', 122);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2232, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2232, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2232, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2232, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2232, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2232, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2233, 6, 2, 'Indique a frequência com a que você desenvolve as seguintes práticas pedagógicas nesta turma: Lidar com temas que aparecem em jornais e/ou revistas, discutindo a relação dos temas com a matemática.', 123);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2233, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2233, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2233, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2233, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2233, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2233, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2234, 6, 2, 'Indique a frequência com a que você desenvolve as seguintes práticas pedagógicas nesta turma: Fornecer esquemas/regras que permitem obter as respostas certas dos cálculos e problemas.', 124);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2234, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2234, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2234, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2234, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2234, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2234, 'F', 'Diariamente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2235, 6, 2, 'Indique a frequência com a que você desenvolve as seguintes práticas pedagógicas nesta turma: Experimentar diferentes ações (coletar informações, recortar, explorar, manipular etc.) para resolver problemas.', 125);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2235, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2235, 'B', 'Uma vez por ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2235, 'C', 'De 3 a 4 vezes ao ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2235, 'D', 'Mensalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2235, 'E', 'Semanalmente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2235, 'F', 'Diariamente.');
