INSERT INTO provabrasil_topics.alunos_5ef
SELECT
  ID_ESCOLA,
  ID_ALUNO,
  ID_BLOCO_1,
  ID_BLOCO_2,
  TX_RESP_BLOCO_1_LP,
  TX_RESP_BLOCO_2_LP,
  TX_RESP_BLOCO_1_MT,
  TX_RESP_BLOCO_2_MT
FROM provabrasil_2013.alunos_5ef
WHERE
   IN_SITUACAO_CENSO = 1
   AND IN_PREENCHIMENTO_PROVA = 1
   AND IN_PROFICIENCIA = 1
   AND IN_PROVA_BRASIL = 1
   AND ID_CADERNO <= 21;

INSERT INTO provabrasil_topics.alunos_9ef
SELECT
  ID_ESCOLA,
  ID_ALUNO,
  ID_BLOCO_1,
  ID_BLOCO_2,
  TX_RESP_BLOCO_1_LP,
  TX_RESP_BLOCO_2_LP,
  TX_RESP_BLOCO_1_MT,
  TX_RESP_BLOCO_2_MT
FROM provabrasil_2013.alunos_9ef
WHERE
   IN_SITUACAO_CENSO = 1
   AND IN_PREENCHIMENTO_PROVA = 1
   AND IN_PROFICIENCIA = 1
   AND IN_PROVA_BRASIL = 1
   AND ID_CADERNO <= 21;