INSERT INTO provabrasil_topics.itens
SELECT
  ID_SERIE,
  DISCIPLINA,
  ID_BLOCO,
  ID_POSICAO,
  ID_ITEM,
  IF(ID_SERIE = 5, substr(DESCRITOR_HABILIDADE, 2), DESCRITOR_HABILIDADE),
  GABARITO
FROM provabrasil_2013.itens
WHERE TIPO_PROVA = 'Prova Regular'
AND ID_SERIE IN (5,9);