INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2000, 6, 1, 'Qual é o seu sexo?', 1);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2000, 'A', 'Masculino.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2000, 'B', 'Feminino.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2001, 6, 1, 'Você poderia nos dizer a sua faixa etária?', 2);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2001, 'A', 'Até 24 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2001, 'B', 'De 25 a 29 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2001, 'C', 'De 30 a 39 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2001, 'D', 'De 40 a 49 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2001, 'E', 'De 50 a 54 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2001, 'F', '55 anos ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2002, 6, 1, 'Como você se considera?', 3);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2002, 'A', 'Branco(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2002, 'B', 'Pardo(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2002, 'C', 'Preto(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2002, 'D', 'Amarelo(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2002, 'E', 'Indígena.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2002, 'F', 'Não quero declarar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2002, 'G', 'Não sei.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2003, 6, 1, 'Qual é o mais alto nível de escolaridade que você concluiu (até a graduação)?', 4);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2003, 'A', 'Menos que o Ensino Médio (antigo 2º grau).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2003, 'B', 'Ensino Médio - Magistério (antigo 2º grau).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2003, 'C', 'Ensino  Médio - Outros (antigo 2º grau).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2003, 'D', 'Ensino Superior - Pedagogia.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2003, 'E', 'Ensino Superior - Curso Normal Superior.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2003, 'F', 'Ensino Superior - Licenciatura em Matemática.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2003, 'G', 'Ensino Superior - Licenciatura em Letras.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2003, 'H', 'Ensino Superior - Outras Licenciaturas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2003, 'I', 'Ensino Superior - Outras áreas.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2004, 6, 1, 'Há quantos anos você obteve o nível de escolaridade assinalado anteriormente (até a graduação)?', 5);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2004, 'A', 'Há menos de 2 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2004, 'B', 'De 2 a 7 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2004, 'C', 'De 8 a 14 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2004, 'D', 'De 15 a 20 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2004, 'E', 'Há mais de 20 anos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2005, 6, 1, 'Indique em que tipo de instituição você obteve seu diploma de ensino superior.', 6);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2005, 'A', 'Não concluí o ensino superior.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2005, 'B', 'Privada.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2005, 'C', 'Pública Federal.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2005, 'D', 'Pública Estadual.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2005, 'E', 'Pública Municipal.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2006, 6, 1, 'De que forma você realizou o curso de ensino superior?', 7);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2006, 'A', 'Não concluí o ensino superior.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2006, 'B', 'Presencial.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2006, 'C', 'Semipresencial.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2006, 'D', 'A distância.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2007, 6, 1, 'Indique o curso de pós-graduação de mais alta titulação que você possui.', 8);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2007, 'A', 'Não fiz ou não completei curso de pós-graduação.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2007, 'B', 'Atualização ou Aperfeiçoamento (mínimo de 180 horas).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2007, 'C', 'Especialização (mínimo de 360 horas).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2007, 'D', 'Mestrado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2007, 'E', 'Doutorado.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2008, 6, 1, 'Indique a área temática do curso de pós-graduação de mais alta titulação que você possui.', 9);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2008, 'A', 'Não fiz ou não completei curso de pós-graduação.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2008, 'B', 'Educação, enfatizando alfabetização.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2008, 'C', 'Educação, enfatizando linguística e/ou letramento.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2008, 'D', 'Educação, enfatizando educação matemática.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2008, 'E', 'Educação - outras ênfases.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2008, 'F', 'Outras áreas que não a Educação.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2009, 6, 1, 'Como diretor, qual é, aproximadamente, o seu salário bruto? (com adicionais, se houver).', 10);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2009, 'A', 'Até R$ 678,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2009, 'B', 'Entre R$ 679,00 e R$ 1.017,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2009, 'C', 'Entre R$ 1.018,00 e R$ 1.356,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2009, 'D', 'Entre R$ 1.357,00 e R$ 1.695,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2009, 'E', 'Entre R$ 1.696,00 e R$ 2.034,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2009, 'F', 'Entre R$ 2.035,00 e R$ 2.373,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2009, 'G', 'Entre R$ 2.374,00 e R$ 2.712,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2009, 'H', 'Entre R$ 2.713,00 e R$ 3.390,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2009, 'I', 'Entre R$ 3.391,00 e R$ 4.746,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2009, 'J', 'Entre R$ 4.747,00 e R$ 6.780,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2009, 'K', 'R$ 6.781,00 ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2010, 6, 1, 'Além da direção desta escola, você exerce outra atividade que contribui para sua renda pessoal?', 11);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2010, 'A', 'Sim, na área de educação.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2010, 'B', 'Sim, fora da área de educação.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2010, 'C', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2011, 6, 1, 'Considerando todas as atividades que você exerce (dentro e fora da área de educação), qual é, aproximadamente, o seu salário bruto? (com adicionais, se houver).', 12);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2011, 'A', 'Até R$ 678,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2011, 'B', 'Entre R$ 679,00 e R$ 1.017,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2011, 'C', 'Entre R$ 1.018,00 e R$ 1.356,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2011, 'D', 'Entre R$ 1.357,00 e R$ 1.695,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2011, 'E', 'Entre R$ 1.696,00 e R$ 2.034,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2011, 'F', 'Entre R$ 2.035,00 e R$ 2.373,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2011, 'G', 'Entre R$ 2.374,00 e R$ 2.712,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2011, 'H', 'Entre R$ 2.713,00 e R$ 3.390,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2011, 'I', 'Entre R$ 3.391,00 e R$ 4.746,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2011, 'J', 'Entre R$ 4.747,00 e R$ 6.780,00.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2011, 'K', 'R$ 6.781,00 ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2012, 6, 1, 'Qual é a sua carga horária de trabalho semanal, como diretor, nesta escola?', 13);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2012, 'A', 'Mais de 40 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2012, 'B', '40 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2012, 'C', 'De 20 a 39 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2012, 'D', 'Menos de 20 horas.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2013, 6, 1, 'Você assumiu a direção desta escola por meio de:', 14);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2013, 'A', 'Concurso público apenas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2013, 'B', 'Eleição apenas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2013, 'C', 'Indicação apenas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2013, 'D', 'Processo seletivo apenas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2013, 'E', 'Processo seletivo e Eleição.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2013, 'F', 'Processo seletivo e Indicação.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2013, 'G', 'Outra forma.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2014, 6, 1, 'Por quanto tempo você trabalhou como professor antes de se tornar diretor?', 15);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2014, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2014, 'B', 'Menos de um ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2014, 'C', '1-2 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2014, 'D', '3-5 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2014, 'E', '6-10 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2014, 'F', '11-15 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2014, 'G', '16-20 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2014, 'H', 'Mais de 20 anos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2015, 6, 1, 'Há quantos anos você exerce funções de direção?', 16);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2015, 'A', 'Menos de um ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2015, 'B', '1-2 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2015, 'C', '3-5 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2015, 'D', '6-10 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2015, 'E', '11-15 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2015, 'F', '16-20 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2015, 'G', 'Mais de 20 anos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2016, 6, 1, 'Há quantos anos você é diretor(a) desta escola?', 17);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2016, 'A', 'Menos de um ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2016, 'B', '1-2 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2016, 'C', '3-5 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2016, 'D', '6-10 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2016, 'E', '11-15 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2016, 'F', '16-20 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2016, 'G', 'Mais de 20 anos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2017, 6, 1, 'Há quantos anos você trabalha na área de educação?', 18);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2017, 'A', 'Menos de um ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2017, 'B', '1-2 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2017, 'C', '3-5 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2017, 'D', '6-10 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2017, 'E', '11-15 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2017, 'F', '16-20 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2017, 'G', 'Mais de 20 anos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2018, 6, 1, 'Durante os últimos dois anos, você participou de alguma atividade de desenvolvimento profissional?', 19);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2018, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2018, 'B', 'Sim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2019, 6, 1, 'Se você participou de alguma atividade de desenvolvimento profissional nos últimos dois anos, como você avalia o impacto da participação em sua atividade como diretor?', 20);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2019, 'A', 'Não participei.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2019, 'B', 'Sim, e não houve impacto.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2019, 'C', 'Sim, e houve um pequeno impacto.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2019, 'D', 'Sim, e houve um impacto moderado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2019, 'E', 'Sim, e houve um grande impacto.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2020, 6, 1, 'Nos últimos dois anos, você gostaria de ter participado de mais atividades de desenvolvimento profissional do que você participou?', 21);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2020, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2020, 'B', 'Sim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2021, 6, 1, 'Se você gostaria de ter participado de mais atividades de desenvolvimento profissional, os seguintes motivos impediram sua participação? O desenvolvimento profissional era muito caro/eu não podia pagar.', 22);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2021, 'A', 'Não gostaria de ter participado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2021, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2021, 'C', 'Sim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2022, 6, 1, 'Se você gostaria de ter participado de mais atividades de desenvolvimento profissional, os seguintes motivos impediram sua participação? Houve conflito com o meu horário de trabalho.', 23);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2022, 'A', 'Não gostaria de ter participado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2022, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2022, 'C', 'Sim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2023, 6, 1, 'Se você gostaria de ter participado de mais atividades de desenvolvimento profissional, os seguintes motivos impediram sua participação? Não tinha disponibilidade de tempo.', 24);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2023, 'A', 'Não gostaria de ter participado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2023, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2023, 'C', 'Sim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2024, 6, 1, 'Se você gostaria de ter participado de mais atividades de desenvolvimento profissional, os seguintes motivos impediram sua participação? Não houve oferta na minha área de interesse.', 25);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2024, 'A', 'Não gostaria de ter participado.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2024, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2024, 'C', 'Sim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2025, 6, 1, 'Nos últimos dois anos, você organizou alguma atividade de formação continuada (atualização, treinamento, capacitação etc.) nesta escola?', 26);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2025, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2025, 'B', 'Sim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2026, 6, 1, 'Qual foi a quantidade de docentes desta escola que participou das atividades de formação continuada que você organizou nos últimos dois anos?', 27);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2026, 'A', 'Não foram organizadas atividades de formação continuada.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2026, 'B', 'Poucos professores.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2026, 'C', 'Um pouco menos da metade dos professores.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2026, 'D', 'Um pouco mais da metade dos professores.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2026, 'E', 'Quase todos ou todos os professores.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2027, 6, 1, 'Qual é o percentual de professores com vínculo estável nesta escola?', 28);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2027, 'A', 'Menor ou igual a 25%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2027, 'B', 'De 26% a 50%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2027, 'C', 'De 51% a 75%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2027, 'D', 'De 76% a 90%.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2027, 'E', 'De 91% a 100%.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2028, 6, 1, 'O Conselho Escolar é um colegiado geralmente constituído por representantes da escola e da comunidade que tem como objetivo acompanhar as atividades escolares. Neste ano, quantas vezes se reuniu o Conselho Escolar?', 29);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2028, 'A', 'Não existe Conselho Escolar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2028, 'B', 'Nenhuma vez.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2028, 'C', 'Uma vez.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2028, 'D', 'Duas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2028, 'E', 'Três vezes ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2029, 6, 1, 'Além de você, quem participa do Conselho Escolar?', 30);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2029, 'A', 'Não existe Conselho Escolar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2029, 'B', 'Professores, funcionários, alunos e pais/responsáveis.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2029, 'C', 'Professores, funcionários e pais/responsáveis.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2029, 'D', 'Professores, alunos e pais/responsáveis.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2029, 'E', 'Professores, funcionários e alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2029, 'F', 'Professores e pais/responsáveis.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2029, 'G', 'Outros.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2030, 6, 1, 'O Conselho de Classe é um orgão formado por todos os professores que lecionam em cada turma/série. Neste ano e nesta escola, quantas vezes se reuniu o Conselho de Classe?', 31);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2030, 'A', 'Não existe Conselho de Classe.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2030, 'B', 'Nenhuma vez.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2030, 'C', 'Uma vez.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2030, 'D', 'Duas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2030, 'E', 'Três vezes ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2031, 6, 1, 'Neste ano e nesta escola, como se deu a elaboração do Projeto Pedagógico?', 32);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2031, 'A', 'Não sei como foi desenvolvido.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2031, 'B', 'Não existe Projeto Pedagógico.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2031, 'C', 'Utilizando-se um modelo pronto, sem discussão com a equipe escolar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2031, 'D', 'Utilizando-se um modelo pronto, mas com discussão com a equipe escolar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2031, 'E', 'Utilizando-se um modelo pronto, porém com adaptações, sem discussão com a equipe escolar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2031, 'F', 'Utilizando-se um modelo pronto, porém com adaptações e com discussão com a equipe escolar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2031, 'G', 'Elaborou-se um modelo próprio, mas não houve discussão com a equipe escolar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2031, 'H', 'Elaborou-se um modelo próprio e houve discussão com a equipe escolar.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2032, 6, 1, 'Esta escola participou da Prova Brasil de 2011?', 33);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2032, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2032, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2032, 'C', 'Não sei.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2033, 6, 1, 'Você conhece os resultados do SAEB (Prova Brasil e/ou ANEB) de 2011? Desta escola?', 34);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2033, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2033, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2033, 'C', 'Minha escola não participou.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2034, 6, 1, 'Você conhece os resultados do SAEB (Prova Brasil e/ou ANEB) de 2011? Do seu município?', 35);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2034, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2034, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2034, 'C', 'Meu município não participou.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2035, 6, 1, 'Você conhece os resultados do SAEB (Prova Brasil e/ou ANEB) de 2011? Do seu estado?', 36);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2035, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2035, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2036, 6, 1, 'Neste ano, qual foi o critério para a admissão de alunos nesta escola?', 37);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2036, 'A', 'Prova de seleção.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2036, 'B', 'Sorteio.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2036, 'C', 'Local de moradia.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2036, 'D', 'Prioridade por ordem de chegada.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2036, 'E', 'Outro critério.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2037, 6, 1, 'Neste ano, como foi a situação da oferta de vagas nesta escola?', 38);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2037, 'A', 'Após o processo de matrícula, a escola ainda tinha vagas disponíveis.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2037, 'B', 'A procura por vaga na escola preencheu todas as vagas oferecidas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2037, 'C', 'A procura por vaga na escola foi um pouco maior que as vagas oferecidas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2037, 'D', 'A procura por vaga na escola superou em muito o número de vagas oferecidas.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2038, 6, 1, 'Neste ano, qual foi o principal critério utilizado para a formação das turmas nesta escola?', 39);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2038, 'A', 'Homogeneidade quanto à idade (alunos com a mesma idade).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2038, 'B', 'Homogeneidade quanto ao rendimento escolar (alunos com rendimento similar).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2038, 'C', 'Heterogeneidade quanto à idade (alunos com idades diferentes).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2038, 'D', 'Heterogeneidade quanto ao rendimento escolar (alunos com rendimentos diferentes).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2038, 'E', 'Outro critério.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2038, 'F', 'Não houve critério.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2039, 6, 1, 'Neste ano, qual foi o principal critério para a atribuição das turmas aos professores?', 40);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2039, 'A', 'Preferência dos professores.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2039, 'B', 'Escolha dos professores, de acordo com a pontuação por tempo de serviço e formação.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2039, 'C', 'Professores experientes com turmas de aprendizagem mais rápida.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2039, 'D', 'Professores experientes com turmas de aprendizagem mais lenta.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2039, 'E', 'Manutenção do professor com a mesma turma.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2039, 'F', 'Revezamento dos professores entre as séries.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2039, 'G', 'Sorteio das turmas entre os professores.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2039, 'H', 'Atribuição pela direção da escola.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2039, 'I', 'Outro critério.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2039, 'J', 'Não houve critério.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2040, 6, 1, 'Nesta escola, há alguma ação para redução das taxas de abandono?', 41);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2040, 'A', 'Não há ação, embora exista o problema.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2040, 'B', 'Não há ação, porque nesta escola não há esse tipo de problema.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2040, 'C', 'Sim, mas com resultados ainda insatisfatórios.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2040, 'D', 'Sim, com resultados satisfatórios.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2040, 'E', 'Sim, mas ainda não avaliamos o resultado.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2041, 6, 1, 'Nesta escola, há alguma ação para redução das taxas de reprovação?', 42);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2041, 'A', 'Não há ação, embora exista o problema.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2041, 'B', 'Não há ação, porque nesta escola não há esse tipo de problema.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2041, 'C', 'Sim, mas com resultados ainda insatisfatórios.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2041, 'D', 'Sim, com resultados satisfatórios.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2041, 'E', 'Sim, mas ainda não avaliamos o resultado.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2042, 6, 1, 'Nesta escola, há alguma ação para o reforço escolar à aprendizagem dos alunos (monitoria, aula de reforço, recuperação etc.)?', 43);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2042, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2042, 'B', 'Sim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2043, 6, 1, 'Nesta escola, indique com que frequência você discute com os professores medidas com o objetivo de melhorar o ensino e a aprendizagem dos alunos.', 44);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2043, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2043, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2043, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2043, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2044, 6, 1, 'Indique com qual frequência são desenvolvidas as seguintes atividades para minimizar as faltas dos alunos neste ano e nesta escola: Os professores conversam com os alunos para tentar solucionar o problema.', 45);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2044, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2044, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2044, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2044, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2045, 6, 1, 'Indique com qual frequência são desenvolvidas as seguintes atividades para minimizar as faltas dos alunos neste ano e nesta escola: Os pais/responsáveis são avisados por comunicação da escola.', 46);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2045, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2045, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2045, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2045, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2046, 6, 1, 'Indique com qual frequência são desenvolvidas as seguintes atividades para minimizar as faltas dos alunos neste ano e nesta escola:  Os pais/responsáveis são chamados à escola para conversar sobre o assunto em reunião de pais.', 47);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2046, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2046, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2046, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2046, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2047, 6, 1, 'Indique com qual frequência são desenvolvidas as seguintes atividades para minimizar as faltas dos alunos neste ano e nesta escola: Os pais/responsáveis são chamados à escola para conversar sobre o assunto individualmente.', 48);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2047, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2047, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2047, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2047, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2048, 6, 1, 'Indique com qual frequência são desenvolvidas as seguintes atividades para minimizar as faltas dos alunos neste ano e nesta escola: A escola envia alguém à casa do aluno.', 49);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2048, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2048, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2048, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2048, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2049, 6, 1, 'Indique com qual frequência você desenvolveu as seguintes atividades neste ano e nesta escola: Desenvolveu atividades extracurriculares em esporte.', 50);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2049, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2049, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2049, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2049, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2050, 6, 1, 'Indique com qual frequência você desenvolveu as seguintes atividades neste ano e nesta escola: Desenvolveu atividades extracurriculares em artes.', 51);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2050, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2050, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2050, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2050, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2051, 6, 1, 'Indique com qual frequência você desenvolveu as seguintes atividades neste ano e nesta escola: Desenvolveu projetos temáticos (ex: bullying, meio ambiente, desigualdades sociais etc).', 52);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2051, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2051, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2051, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2051, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2052, 6, 1, 'Indique com qual frequência você desenvolveu as seguintes atividades neste ano e nesta escola: Neste ano, a escola promoveu eventos para a comunidade.', 53);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2052, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2052, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2052, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2052, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2053, 6, 1, 'Indique com qual frequência você desenvolveu as seguintes atividades neste ano e nesta escola: Os espaços desta escola são utilizados para eventos promovidos pela comunidade.', 54);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2053, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2053, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2053, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2053, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2054, 6, 1, 'Indique com qual frequência você desenvolveu as seguintes atividades neste ano e nesta escola: Neste ano, a comunidade colaborou com trabalho voluntário para esta escola. (por exemplo, desenvolvendo atividades, ajudando na manutenção da escola etc).', 55);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2054, 'A', 'Nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2054, 'B', 'Algumas vezes.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2054, 'C', 'Frequentemente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2054, 'D', 'Sempre ou quase sempre.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2055, 6, 1, 'Quantos estudantes com deficiência ou necessidades especiais estudam nesta escola neste ano?', 56);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2055, 'A', 'Nenhum.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2055, 'B', 'Entre 1 e 5 alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2055, 'C', 'Entre 6 e 10 alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2055, 'D', 'Entre 11 e 20 alunos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2055, 'E', 'Mais de 20 alunos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2056, 6, 1, 'A infraestrutura da escola é adequada às pessoas com deficiência ou necessidades especiais?', 57);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2056, 'A', 'Não');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2056, 'B', 'Sim, mas pouco adequada.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2056, 'C', 'Sim, suficientemente adequada.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2057, 6, 1, 'A escola possui sala de recursos multifuncionais para atendimento educacional especializado (AEE)?', 58);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2057, 'A', 'Não possui sala de recursos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2057, 'B', 'Sim, mas com poucos recursos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2057, 'C', 'Sim, com recursos suficientes.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2058, 6, 1, 'Você possui formação específica para trabalhar com estudantes com deficiência ou necessidades especiais?', 59);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2058, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2058, 'B', 'Sim, mas apenas em uma área/deficiência.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2058, 'C', 'Sim, em mais de uma área/deficiência.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2059, 6, 1, 'Os professores desta escola possuem formação específica para trabalhar com estudantes com deficiência ou necessidades especiais?', 60);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2059, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2059, 'B', 'Sim, mas em número insuficiente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2059, 'C', 'Sim, em número suficiente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2060, 6, 1, 'Os demais funcionários desta escola possuem formação para trabalhar com estudantes com deficiência ou necessidades especiais?', 61);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2060, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2060, 'B', 'Sim, mas em número insuficiente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2060, 'C', 'Sim, em número suficiente.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2061, 6, 1, 'Em relação à merenda escolar, como você avalia os seguintes aspectos: Recursos financeiros.', 62);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2061, 'A', 'Inexistente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2061, 'B', 'Ruim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2061, 'C', 'Razoável.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2061, 'D', 'Bom.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2061, 'E', 'Ótimo.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2062, 6, 1, 'Em relação à merenda escolar, como você avalia os seguintes aspectos: Quantidade de alimentos.', 63);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2062, 'A', 'Inexistente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2062, 'B', 'Ruim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2062, 'C', 'Razoável.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2062, 'D', 'Bom.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2062, 'E', 'Ótimo.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2063, 6, 1, 'Em relação à merenda escolar, como você avalia os seguintes aspectos: Qualidade de alimentos.', 64);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2063, 'A', 'Inexistente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2063, 'B', 'Ruim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2063, 'C', 'Razoável.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2063, 'D', 'Bom.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2063, 'E', 'Ótimo.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2064, 6, 1, 'Em relação à merenda escolar, como você avalia os seguintes aspectos: Espaço físico para cozinhar.', 65);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2064, 'A', 'Inexistente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2064, 'B', 'Ruim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2064, 'C', 'Razoável.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2064, 'D', 'Bom.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2064, 'E', 'Ótimo.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2065, 6, 1, 'Em relação à merenda escolar, como você avalia os seguintes aspectos: Disponibilidade de funcionários.', 66);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2065, 'A', 'Inexistente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2065, 'B', 'Ruim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2065, 'C', 'Razoável.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2065, 'D', 'Bom.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2065, 'E', 'Ótimo.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2066, 6, 1, 'O funcionamento da escola foi dificultado por algum dos seguintes problemas? Insuficiência de recursos financeiros.', 67);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2066, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2066, 'B', 'Sim, pouco.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2066, 'C', 'Sim, moderadamente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2066, 'D', 'Sim, muito.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2067, 6, 1, 'O funcionamento da escola foi dificultado por algum dos seguintes problemas? Inexistência de professores para algumas disciplinas ou séries.', 68);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2067, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2067, 'B', 'Sim, pouco.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2067, 'C', 'Sim, moderadamente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2067, 'D', 'Sim, muito.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2068, 6, 1, 'O funcionamento da escola foi dificultado por algum dos seguintes problemas? Carência de pessoal administrativo.', 69);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2068, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2068, 'B', 'Sim, pouco.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2068, 'C', 'Sim, moderadamente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2068, 'D', 'Sim, muito.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2069, 6, 1, 'O funcionamento da escola foi dificultado por algum dos seguintes problemas? Carência de pessoal de apoio pedagógico (supervisor, coordenador, orientador educacional).', 70);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2069, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2069, 'B', 'Sim, pouco.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2069, 'C', 'Sim, moderadamente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2069, 'D', 'Sim, muito.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2070, 6, 1, 'O funcionamento da escola foi dificultado por algum dos seguintes problemas? Falta de recursos pedagógicos.', 71);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2070, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2070, 'B', 'Sim, pouco.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2070, 'C', 'Sim, moderadamente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2070, 'D', 'Sim, muito.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2071, 6, 1, 'O funcionamento da escola foi dificultado por algum dos seguintes problemas? Interrupção das atividades escolares.', 72);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2071, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2071, 'B', 'Sim, pouco.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2071, 'C', 'Sim, moderadamente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2071, 'D', 'Sim, muito.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2072, 6, 1, 'O funcionamento da escola foi dificultado por algum dos seguintes problemas? Alto índice de faltas por parte dos professores.', 73);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2072, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2072, 'B', 'Sim, pouco.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2072, 'C', 'Sim, moderadamente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2072, 'D', 'Sim, muito.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2073, 6, 1, 'O funcionamento da escola foi dificultado por algum dos seguintes problemas? Alto índice de faltas por parte dos alunos.', 74);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2073, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2073, 'B', 'Sim, pouco.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2073, 'C', 'Sim, moderadamente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2073, 'D', 'Sim, muito.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2074, 6, 1, 'O funcionamento da escola foi dificultado por algum dos seguintes problemas? Alta rotatividade do corpo docente.', 75);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2074, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2074, 'B', 'Sim, pouco.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2074, 'C', 'Sim, moderadamente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2074, 'D', 'Sim, muito.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2075, 6, 1, 'O funcionamento da escola foi dificultado por algum dos seguintes problemas? Indisciplina por parte dos alunos.', 76);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2075, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2075, 'B', 'Sim, pouco.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2075, 'C', 'Sim, moderadamente.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2075, 'D', 'Sim, muito.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2076, 6, 1, 'Considere as condições existentes para o exercício do cargo de diretor nesta escola: Há interferência de atores externos em sua gestão?', 77);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2076, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2076, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2077, 6, 1, 'Considere as condições existentes para o exercício do cargo de diretor nesta escola: Há apoio de instâncias superiores?', 78);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2077, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2077, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2078, 6, 1, 'Considere as condições existentes para o exercício do cargo de diretor nesta escola: Há troca de informações com diretores de outras escolas?', 79);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2078, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2078, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2079, 6, 1, 'Considere as condições existentes para o exercício do cargo de diretor nesta escola: Há apoio da comunidade à sua gestão?', 80);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2079, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2079, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2080, 6, 1, 'Esta escola recebeu neste ano apoio financeiro do governo federal?', 81);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2080, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2080, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2081, 6, 1, 'Esta escola recebeu neste ano apoio financeiro do governo estadual?', 82);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2081, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2081, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2082, 6, 1, 'Esta escola recebeu neste ano apoio financeiro do governo municipal?', 83);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2082, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2082, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2083, 6, 1, 'Esta escola recebeu neste ano apoio financeiro de empresas ou doadores individuais?', 84);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2083, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2083, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2084, 6, 1, 'Para a escolha do livro didático, esta escola utilizou o Guia de Livros Didáticos do MEC?', 85);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2084, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2084, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2085, 6, 1, 'Como se deu a escolha do livro didático neste ano?', 86);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2085, 'A', 'Não sei.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2085, 'B', 'Foi escolhido de forma participativa pelos professores.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2085, 'C', 'Foi escolhido por somente alguns membros da equipe escolar.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2085, 'D', 'Foi escolhido por órgãos externos à escola.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2085, 'E', 'Foi escolhido de outra maneira.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2086, 6, 1, 'Neste ano, nesta escola, ocorreram as seguintes situações: Os livros chegaram em tempo hábil para o início das aulas.', 87);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2086, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2086, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2086, 'C', 'Não sei.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2087, 6, 1, 'Neste ano, nesta escola, ocorreram as seguintes situações: Faltaram livros para os alunos.', 88);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2087, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2087, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2087, 'C', 'Não sei.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2088, 6, 1, 'Neste ano, nesta escola, ocorreram as seguintes situações: Os livros escolhidos foram os recebidos.', 89);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2088, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2088, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2088, 'C', 'Não sei.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2089, 6, 1, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não este ano, nesta escola: Agressão verbal ou física de alunos a professores ou funcionários da escola.', 90);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2089, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2089, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2090, 6, 1, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não este ano, nesta escola: Agressão verbal ou física de alunos a outros alunos da escola.', 91);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2090, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2090, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2091, 6, 1, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não este ano, nesta escola: Você foi vítima de atentado à vida.', 92);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2091, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2091, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2092, 6, 1, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não este ano, nesta escola: Você foi ameaçado por algum aluno.', 93);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2092, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2092, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2093, 6, 1, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não este ano, nesta escola: Você foi vítima de furto (sem uso de violência).', 94);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2093, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2093, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2094, 6, 1, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não este ano, nesta escola: Você foi vítima de roubo (com uso de violência).', 95);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2094, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2094, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2095, 6, 1, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não este ano, nesta escola: Alunos frequentaram a escola sob efeito de bebida alcoólica.', 96);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2095, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2095, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2096, 6, 1, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não este ano, nesta escola: Alunos frequentaram a escola sob efeito de drogas ilícitas.', 97);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2096, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2096, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2097, 6, 1, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não este ano, nesta escola: Alunos frequentaram a escola portando arma branca (facas, canivetes etc).', 98);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2097, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2097, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2098, 6, 1, 'Sobre os fatos listados abaixo, diga se eles aconteceram ou não este ano, nesta escola: Alunos frequentaram a escola portando arma de fogo.', 99);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2098, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2098, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2099, 6, 1, 'Nesta escola, há projetos nas seguintes temáticas: Violência.', 100);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2099, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2099, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2100, 6, 1, 'Nesta escola, há projetos nas seguintes temáticas: Os malefícios do uso de drogas.', 101);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2100, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2100, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2101, 6, 1, 'Nesta escola, há projetos nas seguintes temáticas: Racismo.', 102);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2101, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2101, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2102, 6, 1, 'Nesta escola, há projetos nas seguintes temáticas: Machismo e homofobia.', 103);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2102, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2102, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2103, 6, 1, 'Nesta escola, há projetos nas seguintes temáticas: Bullying.', 104);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2103, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2103, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2104, 6, 1, 'Nesta escola, há projetos nas seguintes temáticas: Sexualidade e gravidez na adolescência.', 105);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2104, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2104, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2105, 6, 1, 'Nesta escola, há projetos nas seguintes temáticas: Desigualdades sociais.', 106);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2105, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2105, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2106, 6, 1, 'Nesta escola, há projetos nas seguintes temáticas: Diversidade religiosa.', 107);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2106, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2106, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2107, 6, 1, 'Nesta escola, há projetos nas seguintes temáticas: Meio ambiente.', 108);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2107, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2107, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2108, 6, 1, 'Nesta escola, o ensino religioso: É de presença obrigatória.', 109);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2108, 'A', 'Não há aula de ensino religioso.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2108, 'B', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2108, 'C', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2109, 6, 1, 'Nesta escola, o ensino religioso: Segue uma religião específica.', 110);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2109, 'A', 'Não há aula de ensino religioso.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2109, 'B', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2109, 'C', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2110, 6, 1, 'Nesta escola, o ensino religioso: Nesta escola há atividades para os estudantes que não queiram participar das aulas de ensino religioso.', 111);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2110, 'A', 'Não há aula de ensino religioso.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2110, 'B', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2110, 'C', 'Não.');
