INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2304, 6, 4, 'Qual é o seu sexo?', 1);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2304, 'A', 'Masculino');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2304, 'B', 'Feminino.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2305, 6, 4, 'Como você se considera?', 2);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2305, 'A', 'Branco(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2305, 'B', 'Pardo(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2305, 'C', 'Preto(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2305, 'D', 'Amarelo(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2305, 'E', 'Indígena.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2305, 'F', 'Não Sei.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2306, 6, 4, 'Você poderia nos dizer qual é o mês de seu aniversário?', 3);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2306, 'A', 'Janeiro.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2306, 'B', 'Fevereiro.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2306, 'C', 'Março.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2306, 'D', 'Abril.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2306, 'E', 'Maio.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2306, 'F', 'Junho.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2306, 'G', 'Julho.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2306, 'H', 'Agosto.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2306, 'I', 'Setembro.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2306, 'J', 'Outubro.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2306, 'K', 'Novembro.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2306, 'L', 'Dezembro.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2307, 6, 4, 'Qual a sua idade?', 4);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2307, 'A', '8 anos ou menos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2307, 'B', '9 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2307, 'C', '10 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2307, 'D', '11 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2307, 'E', '12 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2307, 'F', '13 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2307, 'G', '14 anos.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2307, 'H', '15 anos ou mais');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2308, 6, 4, 'Na sua casa tem televisão em cores?', 5);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2308, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2308, 'B', 'Sim, uma.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2308, 'C', 'Sim, duas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2308, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2308, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2309, 6, 4, 'Na sua casa tem aparelho de rádio?', 6);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2309, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2309, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2309, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2309, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2309, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2310, 6, 4, 'Na sua casa tem videocassete e/ou DVD?', 7);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2310, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2310, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2310, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2310, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2310, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2311, 6, 4, 'Na sua casa tem geladeira?', 8);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2311, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2311, 'B', 'Sim, uma.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2311, 'C', 'Sim, duas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2311, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2311, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2312, 6, 4, 'Na sua casa tem freezer (parte da geladeira duplex)?', 9);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2312, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2312, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2312, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2312, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2312, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2313, 6, 4, 'Na sua casa tem freezer separado da geladeira?', 10);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2313, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2313, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2313, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2313, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2313, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2314, 6, 4, 'Na sua casa tem máquina de lavar roupa (O tanquinho NÃO deve ser considerado)?', 11);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2314, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2314, 'B', 'Sim, uma.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2314, 'C', 'Sim, duas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2314, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2314, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2315, 6, 4, 'Na sua casa tem carro?', 12);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2315, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2315, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2315, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2315, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2315, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2316, 6, 4, 'Na sua casa tem computador?', 13);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2316, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2316, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2316, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2316, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2316, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2317, 6, 4, 'Na sua casa tem banheiro?', 14);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2317, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2317, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2317, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2317, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2317, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2318, 6, 4, 'Na sua casa tem quartos para dormir?', 15);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2318, 'A', 'Não tem.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2318, 'B', 'Sim, um.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2318, 'C', 'Sim, dois.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2318, 'D', 'Sim, três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2318, 'E', 'Sim, quatro ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2319, 6, 4, 'Incluindo você, quantas pessoas vivem atualmente em sua casa?', 16);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2319, 'A', 'Uma, pois moro sozinho(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2319, 'B', 'Duas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2319, 'C', 'Três.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2319, 'D', 'Quatro.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2319, 'E', 'Cinco.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2319, 'F', 'Seis pessoas ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2320, 6, 4, 'Em sua casa trabalha empregado(a) doméstico(a) pelo menos cinco dias por semana?', 17);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2320, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2320, 'B', 'Sim, um(a) empregado(a).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2320, 'C', 'Sim, dois(duas) empregados(as).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2320, 'D', 'Sim, três empregados(as).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2320, 'E', 'Sim, quatro ou mais empregados(as).');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2321, 6, 4, 'Você mora com sua mãe?', 18);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2321, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2321, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2321, 'C', 'Não, mas moro com outra mulher responsável por mim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2322, 6, 4, 'Até que série sua mãe, ou a mulher responsável por você, estudou?', 19);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2322, 'A', 'Nunca estudou.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2322, 'B', 'Não completou a 4.ª série/5.º ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2322, 'C', 'Completou a 4.ª série/5.º ano, mas não completou a 8.ª série/9.º ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2322, 'D', 'Completou a 8.ª série/9.º ano, mas não completou o Ensino Médio.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2322, 'E', 'Completou o Ensino Médio, mas não completou a Faculdade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2322, 'F', 'Completou a Faculdade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2322, 'G', 'Não sei.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2323, 6, 4, 'Sua mãe, ou a mulher responsável por você, sabe ler e escrever?', 20);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2323, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2323, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2324, 6, 4, 'Você vê sua mãe, ou mulher responsável por você, lendo?', 21);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2324, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2324, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2325, 6, 4, 'Você mora com seu pai?', 22);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2325, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2325, 'B', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2325, 'C', 'Não, mas moro com outro homem responsável por mim.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2326, 6, 4, 'Até que série seu pai, ou o homem responsável por você, estudou?', 23);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2326, 'A', 'Nunca estudou.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2326, 'B', 'Não completou a 4.ª série/5.º ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2326, 'C', 'Completou a 4.ª série/5.º ano, mas não completou a 8.ª série/9.º ano.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2326, 'D', 'Completou a 8.ª série/9.º ano, mas não completou o Ensino Médio.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2326, 'E', 'Completou o Ensino Médio, mas não completou a Faculdade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2326, 'F', 'Completou a Faculdade.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2326, 'G', 'Não sei.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2327, 6, 4, 'Seu pai, ou homem responsável por você, sabe ler e escrever?', 24);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2327, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2327, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2328, 6, 4, 'Você vê o seu pai, ou homem responsável por você, lendo?', 25);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2328, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2328, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2329, 6, 4, 'Com qual frequência seus pais, ou responsáveis por você, vão à reunião de pais?', 26);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2329, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2329, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2329, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2330, 6, 4, 'Seus pais ou responsáveis incentivam você a estudar?', 27);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2330, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2330, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2331, 6, 4, 'Seus pais ou responsáveis incentivam você a fazer o dever de casa e/ou os trabalhos da escola?', 28);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2331, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2331, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2332, 6, 4, 'Seus pais ou responsáveis incentivam você a ler?', 29);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2332, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2332, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2333, 6, 4, 'Seus pais ou responsáveis incentivam você a ir a escola e/ou não faltar às aulas?', 30);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2333, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2333, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2334, 6, 4, 'Seus pais ou responsáveis conversam com você sobre o que acontece na escola?', 31);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2334, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2334, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2335, 6, 4, 'Com qual frequência você lê: Jornais.', 32);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2335, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2335, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2335, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2336, 6, 4, 'Com qual frequência você lê: Livros.', 33);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2336, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2336, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2336, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2337, 6, 4, 'Com qual frequência você lê: Revistas em geral.', 34);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2337, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2337, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2337, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2338, 6, 4, 'Com qual frequência você lê: Revistas em quadrinhos (gibis).', 35);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2338, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2338, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2338, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2339, 6, 4, 'Com qual frequência você lê: Notícias na internet (ex.: blog, notícia).Com qual frequência você lê: Notícias na internet (ex.: blog, notícia).', 36);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2339, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2339, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2339, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2340, 6, 4, 'Com qual frequência você costuma ir à/ao: Biblioteca.', 37);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2340, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2340, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2340, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2341, 6, 4, 'Com qual frequência você costuma ir à/ao: Cinema.', 38);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2341, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2341, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2341, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2342, 6, 4, 'Com qual frequência você costuma ir à/ao: Espetáculo ou exposição (teatro, museu, dança ou música).', 39);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2342, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2342, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2342, 'C', 'Nunca ou quase nunca.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2343, 6, 4, 'Em dia de aula, quanto tempo você gasta assistindo à TV, navegando na internet ou jogando jogos eletrônicos?', 40);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2343, 'A', 'Menos de 1 hora.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2343, 'B', 'Entre 1 e 2 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2343, 'C', 'Mais de 2 horas, até 3 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2343, 'D', 'Mais de 3 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2343, 'E', 'Não vejo TV, não navego na internet e não jogo jogos eletrônicos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2344, 6, 4, 'Em dias de aula, quanto tempo você gasta fazendo trabalhos domésticos (ex.: lavando louça, limpando o quintal etc.)?', 41);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2344, 'A', 'Menos de 1 hora.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2344, 'B', 'Entre 1 e 2 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2344, 'C', 'Mais de 2 horas, até 3 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2344, 'D', 'Mais de 3 horas.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2344, 'E', 'Não faço trabalhos domésticos.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2345, 6, 4, 'Atualmente você trabalha fora de casa (recebendo ou não um salário)?', 42);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2345, 'A', 'Sim.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2345, 'B', 'Não.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2346, 6, 4, 'Quando você entrou na escola?', 43);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2346, 'A', 'Na creche (0 a 3 anos).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2346, 'B', 'Na pré-escola (4 a 5 anos).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2346, 'C', 'Na primeira série ou primeiro ano (6 a 7 anos).');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2346, 'D', 'Depois da primeira série.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2347, 6, 4, 'A partir da primeira série ou primeiro ano, em que tipo de escola você estudou?', 44);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2347, 'A', 'Somente em escola pública.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2347, 'B', 'Somente em escola particular.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2347, 'C', 'Em escola pública e em escola particular.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2348, 6, 4, 'Você já foi reprovado?', 45);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2348, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2348, 'B', 'Sim, uma vez.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2348, 'C', 'Sim, duas vezes ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2349, 6, 4, 'Você já abandonou a escola durante o período de aulas e ficou fora da escola o resto do ano?', 46);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2349, 'A', 'Não.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2349, 'B', 'Sim, uma vez.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2349, 'C', 'Sim, duas vezes ou mais.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2350, 6, 4, 'Você faz o dever de casa de Língua Portuguesa?', 47);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2350, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2350, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2350, 'C', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2350, 'D', 'O(A) professor(a) não passa dever de casa.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2351, 6, 4, 'O(A) professor(a) corrige o dever de casa de Língua Portuguesa?', 48);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2351, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2351, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2351, 'C', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2351, 'D', 'O(A) professor(a) não passa dever de casa.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2352, 6, 4, 'Você faz o dever de casa de Matemática?', 49);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2352, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2352, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2352, 'C', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2352, 'D', 'O(A) professor(a) não passa dever de casa.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2353, 6, 4, 'O(A) professor(a) corrige o dever de casa de Matemática?', 50);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2353, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2353, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2353, 'C', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2353, 'D', 'O(A) professor(a) não passa dever de casa.');
INSERT INTO `question` (`id`, `edition_id`, `survey_id`, `text`, `order`) VALUES (2354, 6, 4, 'Você utiliza a biblioteca ou sala de leitura da sua escola?', 51);
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2354, 'A', 'Sempre ou quase sempre.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2354, 'B', 'De vez em quando.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2354, 'C', 'Nunca ou quase nunca.');
INSERT INTO `alternative` (`question_id`, `alternative`, `text`) VALUES(2354, 'D', 'A escola não possui biblioteca ou sala de leitura.');
